//! TT(56) tabu search preserving exact z=1, z=-1, z=i margins and residual mod 4.
//! Weight-two swaps are individually parity-neutral.  Weight-one swaps are
//! accepted singly only with zero boundary syndrome, or in disjoint pairs with
//! equal syndromes.
use std::{collections::{HashSet,VecDeque},env,fs,thread};use std::sync::Arc;use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const L:[usize;4]=[56,56,56,55];const W:[i32;4]=[1,1,2,2];const H:usize=55;
#[derive(Clone)]struct State{a:[Vec<i8>;4],r:[i32;H],e:i64}
#[derive(Clone,Copy)]struct Mv{k:usize,p:usize,q:usize,sig:u64}
impl State{
 fn new(a:[Vec<i8>;4])->Self{let mut s=Self{a,r:[0;H],e:0};s.recompute();s}
 fn recompute(&mut self){self.r=[0;H];for k in 0..4{for d in 1..L[k]{for i in 0..L[k]-d{self.r[d-1]+=W[k]*self.a[k][i]as i32*self.a[k][i+d]as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}
 fn flip(&mut self,k:usize,p:usize){let old=self.a[k][p]as i32;for d in 1..L[k]{let mut z=0;if p+d<L[k]{z+=self.a[k][p+d]as i32}if p>=d{z+=self.a[k][p-d]as i32}let dr=-2*W[k]*old*z;let b=self.r[d-1]as i64;let c=b+dr as i64;self.e+=c*c-b*b;self.r[d-1]+=dr}self.a[k][p]=-self.a[k][p]}
 fn swap(&mut self,m:Mv){debug_assert_ne!(self.a[m.k][m.p],self.a[m.k][m.q]);self.flip(m.k,m.p);self.flip(m.k,m.q)}
 fn rows(&self)->[i32;4]{std::array::from_fn(|k|self.a[k].iter().map(|&x|x as i32).sum())}
 fn alts(&self)->[i32;4]{std::array::from_fn(|k|self.a[k].iter().enumerate().map(|(i,&x)|if i&1==0{x as i32}else{-(x as i32)}).sum())}
 fn z4(&self)->[i32;8]{let mut z=[0;8];for k in 0..4{for(i,&x)in self.a[k].iter().enumerate(){match i&3{0=>z[2*k]+=x as i32,1=>z[2*k+1]+=x as i32,2=>z[2*k]-=x as i32,_=>z[2*k+1]-=x as i32}}}z}
 fn parity0(&self)->bool{self.r.iter().all(|x|x.rem_euclid(4)==0)}
}
fn parse(path:&str)->Option<State>{let text=fs::read_to_string(path).ok()?;let st=text.find("\"sequences\"")?;let b=text[st..].as_bytes();let need:usize=L.iter().sum();let mut v=vec![];let mut i=0;while i<b.len()&&v.len()<need{if b[i]==b'-'&&i+1<b.len()&&b[i+1]==b'1'{v.push(-1);i+=2}else if b[i]==b'1'{v.push(1);i+=1}else{i+=1}}if v.len()!=need{return None}let mut o=0;let a=std::array::from_fn(|k|{let q=v[o..o+L[k]].to_vec();o+=L[k];q});Some(State::new(a))}
fn psig(n:usize,p:usize)->u64{let mut s=0;for d in 1..56{if(p<d)^(p>=n-d){s|=1u64<<(d-1)}}s}
fn moves(s:&State)->Vec<Mv>{let ps:[Vec<u64>;2]=std::array::from_fn(|k|(0..56).map(|p|psig(56,p)).collect());let mut m=vec![];for k in 0..4{for c in 0..4{let mut p=c;while p<L[k]{let mut q=p+4;while q<L[k]{if s.a[k][p]!=s.a[k][q]{m.push(Mv{k,p,q,sig:if k<2{ps[k][p]^ps[k][q]}else{0}})}q+=4}p+=4}}}m}
fn disjoint(a:Mv,b:Mv)->bool{a.k!=b.k||(a.p!=b.p&&a.p!=b.q&&a.q!=b.p&&a.q!=b.q)}
fn token(k:usize,p:usize)->u64{let mut x=((k*56+p+1)as u64).wrapping_mul(0x9e3779b97f4a7c15);x=(x^(x>>30)).wrapping_mul(0xbf58476d1ce4e5b9);x=(x^(x>>27)).wrapping_mul(0x94d049bb133111eb);x^(x>>31)}
fn shash(s:&State)->u64{let mut h=0;for k in 0..4{for p in 0..L[k]{if s.a[k][p]<0{h^=token(k,p)}}}h}
fn mh(h:u64,m:Mv)->u64{h^token(m.k,m.p)^token(m.k,m.q)}
fn norm4(x:[i32;4])->i32{x[0]*x[0]+x[1]*x[1]+2*x[2]*x[2]+2*x[3]*x[3]}
fn norm8(x:[i32;8])->i32{x[0]*x[0]+x[1]*x[1]+x[2]*x[2]+x[3]*x[3]+2*x[4..].iter().map(|v|v*v).sum::<i32>()}
fn verify(s:&State,rows:[i32;4],alts:[i32;4],z4:[i32;8])->State{let q=State::new(s.a.clone());assert_eq!(q.e,s.e);assert_eq!(q.r,s.r);assert!(q.parity0());assert_eq!(q.rows(),rows);assert_eq!(q.alts(),alts);assert_eq!(q.z4(),z4);assert_eq!(norm4(rows),334);assert_eq!(norm4(alts),334);assert_eq!(norm8(z4),334);q}
#[derive(Clone)]struct Pick{state:State,h:u64}
struct Part{best:Option<Pick>,tested:u64}
fn scan(base:Arc<State>,m:Arc<Vec<Mv>>,tabu:Arc<HashSet<u64>>,bh:u64,global:i64,id:usize,parts:usize,seed:u64)->Part{let mut s=(*base).clone();let mut best=None;let mut tested=0;let mut tie=seed;for i in(id..m.len()).step_by(parts){let a=m[i];if a.sig==0{s.swap(a);tested+=1;let h=mh(bh,a);let take=(s.e<global||!tabu.contains(&h))&&best.as_ref().map_or(true,|q:&Pick|s.e<q.state.e||(s.e==q.state.e&&{tie^=tie<<13;tie^=tie>>7;tie^=tie<<17;tie&1==0}));if take{best=Some(Pick{state:s.clone(),h})}s.swap(a)}s.swap(a);for j in i+1..m.len(){let b=m[j];if a.sig==b.sig&&disjoint(a,b){s.swap(b);tested+=1;let h=mh(mh(bh,a),b);let take=(s.e<global||!tabu.contains(&h))&&best.as_ref().map_or(true,|q:&Pick|s.e<q.state.e);if take{best=Some(Pick{state:s.clone(),h})}s.swap(b)}}s.swap(a)}Part{best,tested}}
fn json(s:&State,elapsed:f64,rounds:u64,tested:u64)->String{let seq=s.a.iter().map(|x|format!("[{}]",x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");let r=s.r.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(",");format!("{{\"construction\":\"TT(56)\",\"search\":\"agent exact three-Fourier-margin parity tabu\",\"solved\":{},\"independently_recomputed\":true,\"weights\":[1,1,2,2],\"lengths\":[56,56,56,55],\"energy\":{},\"l1\":{},\"parity_bad\":0,\"elapsed_s\":{},\"rounds\":{},\"exact_moves_tested\":{},\"row_sums\":{:?},\"alternating_row_sums\":{:?},\"z4_components\":{:?},\"row_norm\":334,\"alternating_norm\":334,\"z4_norm\":334,\"residual\":[{}],\"sequences\":[{}]}}\n",s.e==0,s.e,s.r.iter().map(|x|x.abs()).sum::<i32>(),elapsed,rounds,tested,s.rows(),s.alts(),s.z4(),r,seq)}
fn main(){let a:Vec<String>=env::args().collect();let secs=a.get(1).and_then(|x|x.parse().ok()).unwrap_or(300);let threads=a.get(2).and_then(|x|x.parse().ok()).unwrap_or(4);let path=a.get(3).map(String::as_str).expect("checkpoint");let stem=a.get(4).map(String::as_str).unwrap_or("agent_btt_exact");let shell=a.get(5).map(|x|x=="shell").unwrap_or(false);let mut s=parse(path).unwrap();assert!(s.parity0());let(rows,alts,z4)=(s.rows(),s.alts(),s.z4());verify(&s,rows,alts,z4);let mut global=s.clone();let start=Instant::now();let end=start+Duration::from_secs(secs);let mut trail=VecDeque::from([shash(&s)]);let mut rounds=0;let mut tested=0;let mut stale=0;eprintln!("agent_btt seed={} E={} L1={} rows={:?} alts={:?} z4={:?}",path,s.e,s.r.iter().map(|x|x.abs()).sum::<i32>(),rows,alts,z4);
 while Instant::now()<end&&global.e!=0{let mv=Arc::new(moves(&s));let bh=shash(&s);let tabu=Arc::new(trail.iter().copied().collect::<HashSet<_>>());let base=Arc::new(s.clone());let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut hs=vec![];for id in 0..threads{let(b,m,t)=(base.clone(),mv.clone(),tabu.clone());let ge=global.e;hs.push(thread::spawn(move||scan(b,m,t,bh,ge,id,threads,epoch^(id as u64+1).wrapping_mul(0x9e3779b97f4a7c15))))}let mut pick=None;for h in hs{let q=h.join().unwrap();tested+=q.tested;if let Some(x)=q.best{if pick.as_ref().map_or(true,|y:&Pick|x.state.e<y.state.e){pick=Some(x)}}}rounds+=1;let q=match pick{Some(x)=>x,None=>{trail.clear();trail.push_back(bh);continue}};s=verify(&q.state,rows,alts,z4);assert_eq!(shash(&s),q.h);if shell{eprintln!("agent_btt certified_shell one_or_two_min_E={} L1={} tested={}",s.e,s.r.iter().map(|x|x.abs()).sum::<i32>(),tested);if s.e<global.e{global=s.clone();}break}trail.push_back(q.h);while trail.len()>128{trail.pop_front();}if s.e<global.e{global=s.clone();fs::write(format!("{}_live.json",stem),json(&global,start.elapsed().as_secs_f64(),rounds,tested)).unwrap();eprintln!("agent_btt best E={} L1={} round={} tested={} elapsed={:.3}",global.e,global.r.iter().map(|x|x.abs()).sum::<i32>(),rounds,tested,start.elapsed().as_secs_f64());stale=0}else{stale+=1}if stale>32{s=global.clone();trail.push_back(shash(&s));stale=0}}
 let ans=verify(&global,rows,alts,z4);let out=format!("{}_{}.json",stem,if ans.e==0{"candidate"}else{"summary"});fs::write(&out,json(&ans,start.elapsed().as_secs_f64(),rounds,tested)).unwrap();println!("agent_btt result solved={} E={} L1={} rounds={} tested={} output={}",ans.e==0,ans.e,ans.r.iter().map(|x|x.abs()).sum::<i32>(),rounds,tested,out)}
