//! Exact three-swap syndrome-MITM tabu search in a fixed BS quartic fibre.
use std::{collections::{HashMap,HashSet,VecDeque},env,fs,thread};
use std::sync::Arc;use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const L:[usize;4]=[84,84,83,83];const H:usize=83;
#[derive(Clone)]struct State{a:[Vec<i8>;4],r:[i32;H],e:i64}
#[derive(Clone,Copy)]struct Mv{k:usize,p:usize,q:usize,sig:u128}
impl State{
 fn new(a:[Vec<i8>;4])->Self{let mut s=Self{a,r:[0;H],e:0};s.recompute();s}
 fn recompute(&mut self){self.r=[0;H];for k in 0..4{for d in 1..L[k]{for i in 0..L[k]-d{self.r[d-1]+=self.a[k][i]as i32*self.a[k][i+d]as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}
 fn flip(&mut self,k:usize,p:usize){let old=self.a[k][p]as i32;for d in 1..L[k]{let mut z=0;if p+d<L[k]{z+=self.a[k][p+d]as i32}if p>=d{z+=self.a[k][p-d]as i32}let dr=-2*old*z;let b=self.r[d-1]as i64;let c=b+dr as i64;self.e+=c*c-b*b;self.r[d-1]+=dr}self.a[k][p]=-self.a[k][p]}
 fn swap(&mut self,m:Mv){debug_assert_ne!(self.a[m.k][m.p],self.a[m.k][m.q]);self.flip(m.k,m.p);self.flip(m.k,m.q)}
 fn parity0(&self)->bool{self.r.iter().all(|x|x.rem_euclid(4)==0)}
 fn rows(&self)->[i32;4]{std::array::from_fn(|k|self.a[k].iter().map(|&x|x as i32).sum())}
 fn alts(&self)->[i32;4]{std::array::from_fn(|k|self.a[k].iter().enumerate().map(|(i,&x)|if i&1==0{x as i32}else{-(x as i32)}).sum())}
 fn z4(&self)->[i32;8]{let mut z=[0;8];for k in 0..4{for(i,&x)in self.a[k].iter().enumerate(){match i&3{0=>z[2*k]+=x as i32,1=>z[2*k+1]+=x as i32,2=>z[2*k]-=x as i32,_=>z[2*k+1]-=x as i32}}}z}
}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next()as usize%n}}
fn parse(path:&str)->Option<State>{let text=fs::read_to_string(path).ok()?;let st=text.find("\"sequences\"")?;let b=text[st..].as_bytes();let need:usize=L.iter().sum();let mut v=vec![];let mut i=0;while i<b.len()&&v.len()<need{if b[i]==b'-'&&i+1<b.len()&&b[i+1]==b'1'{v.push(-1);i+=2}else if b[i]==b'1'{v.push(1);i+=1}else{i+=1}}if v.len()!=need{return None}let mut o=0;let a=std::array::from_fn(|k|{let x=v[o..o+L[k]].to_vec();o+=L[k];x});Some(State::new(a))}
fn position_sig(n:usize,p:usize)->u128{let mut s=0;for d in 1..84{if(p<d)^(p>=n-d){s|=1u128<<(d-1)}}s}
fn moves(s:&State)->Vec<Mv>{let sigs:[Vec<u128>;4]=std::array::from_fn(|k|(0..L[k]).map(|p|position_sig(L[k],p)).collect());let mut out=vec![];for k in 0..4{for c in 0..4{let mut p=c;while p<L[k]{let mut q=p+4;while q<L[k]{if s.a[k][p]!=s.a[k][q]{out.push(Mv{k,p,q,sig:sigs[k][p]^sigs[k][q]})}q+=4}p+=4}}}out}
fn disjoint(a:Mv,b:Mv)->bool{a.k!=b.k||(a.p!=b.p&&a.p!=b.q&&a.q!=b.p&&a.q!=b.q)}
fn hash(s:&State)->u64{let mut h=0xcbf29ce484222325;for x in&s.a{for&v in x{h^=(v as i16+2)as u64;h=h.wrapping_mul(0x100000001b3)}}h}
fn verify(s:&State,rows:[i32;4],alts:[i32;4],z4:[i32;8])->State{let t=State::new(s.a.clone());assert_eq!(t.e,s.e);assert_eq!(t.r,s.r);assert!(t.parity0());assert_eq!(t.rows(),rows);assert_eq!(t.alts(),alts);assert_eq!(t.z4(),z4);t}
fn json(s:&State,elapsed:f64,rounds:u64,triples:u64)->String{let seq=s.a.iter().map(|x|format!("[{}]",x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");let r=s.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");format!("{{\"construction\":\"base sequences BS(84,83)\",\"search\":\"agent exact 3-swap syndrome MITM tabu\",\"solved\":{},\"independently_recomputed\":true,\"energy\":{},\"l1\":{},\"parity_bad\":0,\"elapsed_s\":{},\"rounds\":{},\"exact_triples_tested\":{},\"row_sums\":{:?},\"alternating_sums\":{:?},\"z4_components\":{:?},\"residual\":[{}],\"sequences\":[{}]}}\n",s.e==0,s.e,s.r.iter().map(|x|x.abs()).sum::<i32>(),elapsed,rounds,triples,s.rows(),s.alts(),s.z4(),r,seq)}
struct Part{best:Option<State>,exact:u64}
fn scan(base:Arc<State>,mv:Arc<Vec<Mv>>,pairs:Arc<HashMap<u128,Vec<(u16,u16)>>>,tabu:Arc<HashSet<u64>>,part:usize,parts:usize,global:i64,seed:u64)->Part{let mut s=(*base).clone();let mut best=None;let mut exact=0;let mut rng=Rng(seed);for t in(part..mv.len()).step_by(parts){if let Some(ps)=pairs.get(&mv[t].sig){for&(ii,jj)in ps{let(i,j)=(ii as usize,jj as usize);if j>=t||!disjoint(mv[i],mv[t])||!disjoint(mv[j],mv[t]){continue}s.swap(mv[i]);s.swap(mv[j]);s.swap(mv[t]);debug_assert!(s.parity0());exact+=1;let allowed=s.e<global||!tabu.contains(&hash(&s));let take=allowed&&best.as_ref().map_or(true,|b:&State|s.e<b.e||(s.e==b.e&&rng.usize(2)==0));if take{best=Some(s.clone())}s.swap(mv[t]);s.swap(mv[j]);s.swap(mv[i]);}}}Part{best,exact}}
fn main(){let a:Vec<String>=env::args().collect();let secs=a.get(1).and_then(|x|x.parse().ok()).unwrap_or(600);let threads=a.get(2).and_then(|x|x.parse().ok()).unwrap_or(4);let path=a.get(3).map(String::as_str).expect("checkpoint");let mut s=parse(path).unwrap();assert!(s.parity0());let(rows,alts,z4)=(s.rows(),s.alts(),s.z4());let mut global=s.clone();let mut trail=VecDeque::from([hash(&s)]);let start=Instant::now();let end=start+Duration::from_secs(secs);let mut rounds=0;let mut total=0;let mut stale=0;eprintln!("agent_bsd_triple seed={} energy={} l1={} rows={:?} alts={:?} z4={:?}",path,s.e,s.r.iter().map(|x|x.abs()).sum::<i32>(),rows,alts,z4);
 while Instant::now()<end&&global.e!=0{let m=Arc::new(moves(&s));let mut map:HashMap<u128,Vec<(u16,u16)>>=HashMap::new();for i in 0..m.len(){for j in i+1..m.len(){if disjoint(m[i],m[j]){map.entry(m[i].sig^m[j].sig).or_default().push((i as u16,j as u16));}}}let map=Arc::new(map);let base=Arc::new(s.clone());let tabu:Arc<HashSet<u64>>=Arc::new(trail.iter().copied().collect());let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut hs=vec![];for id in 0..threads{let(b,m,p,t)=(base.clone(),m.clone(),map.clone(),tabu.clone());let ge=global.e;hs.push(thread::spawn(move||scan(b,m,p,t,id,threads,ge,epoch^(id as u64+1)*0x9e3779b9)))}let mut pick=None;for h in hs{let x=h.join().unwrap();total+=x.exact;if let Some(q)=x.best{if pick.as_ref().map_or(true,|b:&State|q.e<b.e){pick=Some(q)}}}rounds+=1;let next=match pick{Some(x)=>x,None=>{trail.clear();trail.push_back(hash(&s));continue}};if next.e<global.e{global=verify(&next,rows,alts,z4);fs::write("agent_bsd_e896_triple_live.json",json(&global,start.elapsed().as_secs_f64(),rounds,total)).unwrap();eprintln!("agent_bsd_triple best energy={} l1={} round={} exact={} elapsed_s={:.3}",global.e,global.r.iter().map(|x|x.abs()).sum::<i32>(),rounds,total,start.elapsed().as_secs_f64());stale=0}else{stale+=1}s=next;trail.push_back(hash(&s));while trail.len()>96{trail.pop_front();}if stale>16{s=global.clone();trail.clear();trail.push_back(hash(&s));stale=0}}
 let ans=verify(&global,rows,alts,z4);let out=if ans.e==0{"agent_bsd_e896_triple_candidate.json"}else{"agent_bsd_e896_triple_summary.json"};fs::write(out,json(&ans,start.elapsed().as_secs_f64(),rounds,total)).unwrap();println!("agent_bsd_triple result solved={} energy={} l1={} rounds={} exact_triples={} output={}",ans.e==0,ans.e,ans.r.iter().map(|x|x.abs()).sum::<i32>(),rounds,total,out)}
