"""Enumerate ALL subgroups of Z_333^* and their orbit structure on Z_333.

Z_333^* has order phi(333)=216 and is abelian of rank <= 2, so every subgroup
is generated by at most two elements. We enumerate closures of all pairs.
For each subgroup K we report the number of orbits on Z_333 (= free bits per
sequence in a K-invariant Legendre-pair ansatz) so fibers can be attacked in
order of decidability.
"""
import json, math
N = 333
units = [x for x in range(1, N) if math.gcd(x, N) == 1]
assert len(units) == 216

def closure(gens):
    s = {1}
    frontier = {1}
    while frontier:
        nxt = set()
        for a in frontier:
            for g in gens:
                v = a * g % N
                if v not in s:
                    s.add(v); nxt.add(v)
        frontier = nxt
    return frozenset(s)

subs = set()
for i, g1 in enumerate(units):
    subs.add(closure((g1,)))
# pairs (this is 216^2/2 closures; keep it feasible by using found cyclic subs as bases)
cyclic = sorted(subs, key=len)
for a in units:
    for b in units:
        if b <= a: continue
        subs.add(closure((a, b)))

def orbit_count(K):
    seen = [False]*N
    n_orb = 0
    sizes = {}
    for i in range(N):
        if seen[i]: continue
        o = {i*g % N for g in K}
        for x in o: seen[x] = True
        n_orb += 1
        sizes[len(o)] = sizes.get(len(o), 0) + 1
    return n_orb, sizes

rows = []
for K in subs:
    n_orb, sizes = orbit_count(K)
    rows.append({"order": len(K), "orbits": n_orb, "bits_per_seq": n_orb,
                 "total_bits": 2*n_orb, "contains_minus1": (N-1) in K,
                 "orbit_sizes": sizes, "members_sample": sorted(K)[:6]})
rows.sort(key=lambda r: (r["total_bits"], -r["order"]))
print(f"total distinct subgroups: {len(subs)}")
for r in rows:
    print(json.dumps(r, separators=(",", ":")))
