//! Parity-feasible native search for base sequences BS(84,83).
//! Such a witness feeds directly into a Goethals-Seidel array of order 668.

use std::{env,fs,thread};
use std::sync::{Arc,Mutex};
use std::sync::atomic::{AtomicBool,AtomicI64,Ordering};
use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const L:[usize;4]=[84,84,83,83];

#[derive(Clone)] struct State{a:Vec<Vec<i8>>,r:[i32;83],e:i64}
impl State{
 fn new(a:Vec<Vec<i8>>)->Self{let mut s=Self{a,r:[0;83],e:0};s.recompute();s}
 fn recompute(&mut self){self.r=[0;83];for d in 1..84{for k in 0..4{for i in 0..self.a[k].len()-d{self.r[d-1]+=self.a[k][i] as i32*self.a[k][i+d] as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}
 fn flip(&mut self,k:usize,p:usize){let old=self.a[k][p] as i32;let n=self.a[k].len();for d in 1..84{let mut z=0;if p+d<n{z+=self.a[k][p+d] as i32}if p>=d{z+=self.a[k][p-d] as i32}let delta=-2*old*z;let b=self.r[d-1] as i64;let c=b+delta as i64;self.e+=c*c-b*b;self.r[d-1]+=delta}self.a[k][p]=-self.a[k][p]}
 fn weighted(&self,w:&[i64;83])->i64{let base:i64=self.r.iter().zip(w).map(|(&x,&y)|y*(x as i64)*(x as i64)).sum();let total:i64=self.r.iter().map(|&x|x as i64).sum();base+total*total/4}
 fn weighted_l1(&self,w:&[i64;83])->i64{let base:i64=self.r.iter().zip(w).map(|(&x,&y)|y*x.abs() as i64).sum();let total:i64=self.r.iter().map(|&x|x as i64).sum();base+2*total.abs()}
 fn parity_bad(&self)->i64{self.r.iter().filter(|&&x|x.rem_euclid(4)!=0).count()as i64}
 fn objective(&self,w:&[i64;83],l1:bool,rank:bool)->i64{let base=if l1{self.weighted_l1(w)}else{self.weighted(w)};base+if rank{4096*self.parity_bad()}else{0}}
 fn metric(&self,rank:bool)->i64{self.e+if rank{4096*self.parity_bad()}else{0}}
 fn rows(&self)->[i32;4]{let mut x=[0;4];for k in 0..4{x[k]=self.a[k].iter().map(|&v|v as i32).sum()}x}
}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next() as usize%n}fn unit(&mut self)->f64{(self.next()>>11)as f64/(1u64<<53)as f64}}

fn seed()->State{let mut a=L.iter().map(|&n|vec![1i8;n]).collect::<Vec<_>>();a[0][0]=-1;State::new(a)}
fn parse_seed(path:&str)->Option<State>{let text=fs::read_to_string(path).ok()?;let start=text.find("\"sequences\"")?;let bytes=text[start..].as_bytes();let mut values=Vec::with_capacity(334);let mut i=0;while i<bytes.len()&&values.len()<334{if bytes[i]==b'-'&&i+1<bytes.len()&&bytes[i+1]==b'1'{values.push(-1);i+=2}else if bytes[i]==b'1'{values.push(1);i+=1}else{i+=1}}if values.len()!=334{return None}let mut a=vec![];let mut p=0;for &n in &L{a.push(values[p..p+n].to_vec());p+=n}Some(State::new(a))}

fn basis_move(s:&mut State,rng:&mut Rng,undo:&mut[(usize,usize);64],used:&mut usize){
 let g=rng.usize(85);
 if g<42{let i=g;let c=[(0,i),(0,83-i),(1,i),(1,83-i)];let x=rng.usize(4);let mut y=rng.usize(3);if y>=x{y+=1}undo[*used]=c[x];undo[*used+1]=c[y];s.flip(c[x].0,c[x].1);s.flip(c[y].0,c[y].1);*used+=2}
 else if g<83{let i=g-42;let c=[(2,i),(2,82-i),(3,i),(3,82-i)];let x=rng.usize(4);let mut y=rng.usize(3);if y>=x{y+=1}undo[*used]=c[x];undo[*used+1]=c[y];s.flip(c[x].0,c[x].1);s.flip(c[y].0,c[y].1);*used+=2}
 else{let p=(g-81,41);undo[*used]=p;s.flip(p.0,p.1);*used+=1}
}
fn row_move(s:&mut State,rng:&mut Rng,undo:&mut[(usize,usize);64],used:&mut usize){
 let k=rng.usize(4);let n=s.a[k].len();let mut p=rng.usize(n);while s.a[k][p]!=1{p=rng.usize(n)}let mut q=rng.usize(n);while s.a[k][q]!=-1{q=rng.usize(n)}undo[*used]=(k,p);undo[*used+1]=(k,q);s.flip(k,p);s.flip(k,q);*used+=2
}
fn row_parity_move(s:&mut State,rng:&mut Rng,undo:&mut[(usize,usize);64],used:&mut usize){
 // Flipping both members of a reversal orbit preserves every aperiodic
 // autocorrelation modulo 4.  An antisymmetric orbit preserves the row sum;
 // alternatively a ++ orbit balanced with a -- orbit does so.  These direct
 // moves avoid the expensive rejection search used by the fallback below.
 if rng.usize(5)<4{
  let k=rng.usize(4);let n=s.a[k].len();let h=n/2;
  if rng.usize(3)<2{
   for _ in 0..64{let p=rng.usize(h);let q=n-1-p;if s.a[k][p]!=s.a[k][q]{undo[*used]=(k,p);undo[*used+1]=(k,q);s.flip(k,p);s.flip(k,q);*used+=2;return}}
  }else{
   let(mut pp,mut mm)=(None,None);for _ in 0..128{let p=rng.usize(h);let q=n-1-p;let z=s.a[k][p]+s.a[k][q];if z==2{pp=Some(p)}else if z== -2{mm=Some(p)}if pp.is_some()&&mm.is_some(){break}}
   if let(Some(p),Some(q))=(pp,mm){for x in [p,n-1-p,q,n-1-q]{undo[*used]=(k,x);s.flip(k,x);*used+=1}return}
  }
 }
 let rows=s.rows();for _ in 0..64{let start=*used;for _ in 0..(2+rng.usize(3)){basis_move(s,rng,undo,used)}if s.rows()==rows{return}for &(k,p) in undo[start..*used].iter().rev(){s.flip(k,p)}*used=start}
}
fn search_move(s:&mut State,rng:&mut Rng,row:bool,row_parity:bool,undo:&mut[(usize,usize);64],used:&mut usize){if row_parity{row_parity_move(s,rng,undo,used)}else if row{row_move(s,rng,undo,used)}else{basis_move(s,rng,undo,used)}}
fn make_row_valid(s:&mut State){let rows=s.rows();let mut target=rows;let mut best=i32::MAX;for a in (-20i32..=20).step_by(2){for b in (-20i32..=20).step_by(2){for c in (-19i32..=19).step_by(2){for d in (-19i32..=19).step_by(2){if a*a+b*b+c*c+d*d==334{let z=[a,b,c,d];let dist=(0..4).map(|k|(z[k]-rows[k]).abs()).sum();if dist<best{best=dist;target=z}}}}}}for k in 0..4{while s.rows()[k]!=target[k]{let current=s.rows()[k];let needed=if target[k]>current{-1}else{1};let mut best_p=0;let mut best_score=i64::MAX;for p in 0..s.a[k].len(){if s.a[k][p]!=needed{continue}s.flip(k,p);let score=s.weighted(&[1i64;83]);s.flip(k,p);if score<best_score{best_score=score;best_p=p}}s.flip(k,best_p)}}assert_eq!(s.rows().iter().map(|x|x*x).sum::<i32>(),334);eprintln!("row-valid seed energy={} rows={:?}",s.e,s.rows())}
fn force_row_tuple(s:&mut State,target:[i32;4]){assert_eq!(target.iter().map(|x|x*x).sum::<i32>(),334);for k in 0..4{assert_eq!((target[k]-L[k]as i32).rem_euclid(2),0);while s.rows()[k]!=target[k]{let current=s.rows()[k];let needed=if target[k]>current{-1}else{1};let mut best_p=0;let mut best_score=i64::MAX;for p in 0..s.a[k].len(){if s.a[k][p]!=needed{continue}s.flip(k,p);let score=s.weighted(&[1i64;83]);s.flip(k,p);if score<best_score{best_score=score;best_p=p}}s.flip(k,best_p)}}assert_eq!(s.rows(),target);eprintln!("forced row seed energy={} parity_bad={} rows={:?}",s.e,s.parity_bad(),s.rows())}
fn parse_row_tuple(x:&str)->[i32;4]{let v=x.split(',').map(|y|y.parse::<i32>().unwrap()).collect::<Vec<_>>();if v.len()!=4{panic!("row tuple needs four integers")}[v[0],v[1],v[2],v[3]]}
fn make_row_parity_valid(s:&mut State){let mut rng=Rng(668);let mut best=s.clone();let mut best_gap=(s.rows().iter().map(|x|x*x).sum::<i32>()-334).abs();if best_gap==0{eprintln!("row+parity-valid seed energy={} rows={:?}",s.e,s.rows());return}for step in 0..2_000_000usize{let before=s.clone();let mut undo=[(0usize,0usize);64];let mut used=0;basis_move(s,&mut rng,&mut undo,&mut used);let norm=s.rows().iter().map(|x|x*x).sum::<i32>();let gap=(norm-334).abs();if gap<best_gap{best_gap=gap;best=s.clone();if gap==0{*s=best;eprintln!("row+parity-valid seed energy={} rows={:?}",s.e,s.rows());return}}let old_gap=(before.rows().iter().map(|x|x*x).sum::<i32>()-334).abs();let temp=40.0*(0.001f64).powf((step%20000)as f64/20000.0)+0.1;let delta=(gap-old_gap)as f64;if delta>0.0&&rng.unit()>=(-delta/temp).exp(){*s=before}if step%20000==19999{*s=best.clone()}}panic!("failed to reach a row-valid parity state; best gap {}",best_gap)}
fn update(s:&State,id:usize,start:Instant,atom:&AtomicI64,best:&Mutex<State>,rank:bool){let metric=s.metric(rank);let mut seen=atom.load(Ordering::Relaxed);while metric<seen{match atom.compare_exchange_weak(seen,metric,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=s.clone();let seqs=s.a.iter().map(|a|format!("[{}]",a.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");let residual=s.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");let name=if rank{"bs_84_83_row_rank_live.json"}else if s.rows()==[10,8,-1,-13]{"bs_84_83_live.json"}else{"bs_84_83_alt_live.json"};let _=fs::write(format!("Find a Hadamard matrix of order 668/{}",name),format!("{{\"metric\":{},\"energy\":{},\"parity_bad\":{},\"row_sums\":{:?},\"residual\":[{}],\"sequences\":[{}]}}\n",metric,s.e,s.parity_bad(),s.rows(),residual,seqs));eprintln!("best metric={} energy={} parity_bad={} worker={} elapsed_s={:.3} rows={:?}",metric,s.e,s.parity_bad(),id,start.elapsed().as_secs_f64(),s.rows());return},Err(x)=>seen=x}}}
fn worker(id:usize,end:Instant,start:Instant,atom:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>,row:bool,row_parity:bool,rank:bool)->u64{
 let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(epoch^(id as u64+1).wrapping_mul(0x9e3779b97f4a7c15));let mut moves=0;
 while Instant::now()<end&&!stop.load(Ordering::Relaxed){let mut s=best.lock().unwrap().clone();for _ in 0..rng.usize(80){let mut u=[(0,0);64];let mut n=0;search_move(&mut s,&mut rng,row,row_parity,&mut u,&mut n)}let mut w=[1i64;83];let mut stale=0usize;let mut local=s.metric(rank);
  for step in 0..300000{if step&8191==0&&(Instant::now()>=end||stop.load(Ordering::Relaxed)){break}let phase=step as f64/300000.0;let t=(if id%3==0{1200.0}else if id%3==1{400.0}else{120.0})*(0.0005f64).powf(phase)+0.05;let roll=rng.usize(1000);let count=if roll<650{1}else if roll<930{2}else if roll<990{3}else{4+rng.usize(5)};let l1=id%4==2;let before=s.objective(&w,l1,rank);let mut undo=[(0usize,0usize);64];let mut used=0;if id%4==3&&count==1{let mut best_move=[(0usize,0usize);64];let mut best_used=0;let mut best_score=i64::MAX;for _ in 0..512{let mut trial=[(0usize,0usize);64];let mut n=0;search_move(&mut s,&mut rng,row,row_parity,&mut trial,&mut n);let score=s.objective(&w,l1,rank);for &(k,p) in trial[..n].iter().rev(){s.flip(k,p)}if score<best_score{best_score=score;best_used=n;best_move[..n].copy_from_slice(&trial[..n])}}for &(k,p) in &best_move[..best_used]{s.flip(k,p);undo[used]=(k,p);used+=1}}else{for _ in 0..count{search_move(&mut s,&mut rng,row,row_parity,&mut undo,&mut used)}}moves+=1;let delta=s.objective(&w,l1,rank)-before;if delta>0&&rng.unit()>=(-(delta as f64)/t).exp(){for &(k,p) in undo[..used].iter().rev(){s.flip(k,p)}}else if s.metric(rank)<local{local=s.metric(rank);stale=0;update(&s,id,start,&atom,&best,rank);if s.e==0{let mut check=s.clone();check.recompute();if check.e==0{*best.lock().unwrap()=check;stop.store(true,Ordering::SeqCst);break}}}else{stale+=1}if id%2==1&&stale>40000{for j in 0..83{if s.r[j]!=0{w[j]=(w[j]+1+(s.r[j].abs()/4)as i64).min(64)}}stale=0}else if stale>80000{for _ in 0..(12+rng.usize(30)){let mut u=[(0,0);64];let mut n=0;search_move(&mut s,&mut rng,row,row_parity,&mut u,&mut n)}stale=0}}
 }moves
}
fn main(){let z:Vec<String>=env::args().collect();let secs=z.get(1).and_then(|x|x.parse().ok()).unwrap_or(600);let threads=z.get(2).and_then(|x|x.parse().ok()).unwrap_or(8);let mode=z.get(4).map(String::as_str).unwrap_or("");let rank=mode=="row_rank";let row=mode=="row"||rank;let row_parity=mode=="row_parity";let mut initial=z.get(3).and_then(|p|parse_seed(p)).unwrap_or_else(seed);if let Some(x)=z.get(5){force_row_tuple(&mut initial,parse_row_tuple(x))}else if row{make_row_valid(&mut initial)}else if row_parity{make_row_parity_valid(&mut initial)}eprintln!("seed metric={} energy={} parity_bad={} rows={:?}",initial.metric(rank),initial.e,initial.parity_bad(),initial.rows());let start=Instant::now();let end=start+Duration::from_secs(secs);let atom=Arc::new(AtomicI64::new(initial.metric(rank)));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let a=atom.clone();let b=best.clone();let s=stop.clone();hs.push(thread::spawn(move||worker(id,end,start,a,b,s,row,row_parity,rank)))}let moves:u64=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut ans=best.lock().unwrap().clone();ans.recompute();let ok=ans.e==0;let seqs=ans.a.iter().map(|a|format!("[{}]",a.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",\n    ");let residual=ans.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");let json=format!("{{\n  \"construction\": \"base sequences BS(84,83)\",\n  \"solved\": {},\n  \"metric\": {},\n  \"energy\": {},\n  \"parity_bad\": {},\n  \"elapsed_s\": {:.6},\n  \"moves\": {},\n  \"row_sums\": {:?},\n  \"residual\": [{}],\n  \"sequences\": [\n    {}\n  ]\n}}\n",ok,ans.metric(rank),ans.e,ans.parity_bad(),start.elapsed().as_secs_f64(),moves,ans.rows(),residual,seqs);let alt=ans.rows()!=[10,8,-1,-13];let path=if ok{"Find a Hadamard matrix of order 668/bs_84_83_candidate.json"}else if rank{"Find a Hadamard matrix of order 668/bs_84_83_row_rank_summary.json"}else if row_parity&&alt{"Find a Hadamard matrix of order 668/bs_84_83_alt_parity_summary.json"}else if row_parity{"Find a Hadamard matrix of order 668/bs_84_83_row_parity_summary.json"}else if row{"Find a Hadamard matrix of order 668/bs_84_83_row_summary.json"}else{"Find a Hadamard matrix of order 668/bs_84_83_summary.json"};fs::write(path,json).unwrap();println!("result solved={} metric={} energy={} parity_bad={} rows={:?} moves={} elapsed_s={:.3} output={}",ok,ans.metric(rank),ans.e,ans.parity_bad(),ans.rows(),moves,start.elapsed().as_secs_f64(),path)}
