"""Second-level split of the surviving <271> sub-fibers.

Within a sub-fiber (fixed 5-of-9 fixed-point patterns pa, pb), each sequence
has 36 nine-orbit bits organized as 4 class-columns x 9 rows (columns = the
four cosets of <12> in Z_37^*, rows = Z_9). We branch on the exact number of
ones per column, (k0..k3) with sum 18, for both sequences: 4 cardinality
equalities per sequence replace the single sum=18, giving presolve exact
per-column counts. The full set of (kA, kB) composition pairs partitions the
sub-fiber, so an all-INFEASIBLE pass decides it.

Column composition symmetry: multiplying the 37-part by a unit permutes the
four cosets cyclically (through the quotient Z_37^*/<12> = Z_4 generated by a
nonresidue); this acts simultaneously on both sequences' columns and leaves
the fixed-point patterns untouched, so composition pairs are deduped under
the cyclic C_4 rotation.
"""
import argparse, itertools, json, sys, time
from collections import Counter
from pathlib import Path
from ortools.sat.python import cp_model

import importlib.util
spec = importlib.util.spec_from_file_location("sp", "search_lp333_271_split.py")
sp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sp)

N = 333
K = sp.K
orbs, own, sizes = sp.orbs, sp.own, sp.sizes
fixed, nines, fix_by_m = sp.fixed, sp.nines, sp.fix_by_m

# class-column of each nine-orbit: the coset of <12> in Z_37^* containing the
# orbit's 37-part. Orbit elements share (x mod 9) constant? No: orbit of x under
# multiplication by 271 (=1 mod 9, order-9 mod 37): x mod 9 is CONSTANT on the
# orbit; x mod 37 ranges over a coset of <12>. So each nine-orbit is labeled by
# (row r = x mod 9, column c = coset of x mod 37).
g37 = 2  # find a generator of Z_37^*
def order_mod37(g):
    x, k = 1, 0
    while True:
        x = x * g % 37; k += 1
        if x == 1: return k
while order_mod37(g37) != 36:
    g37 += 1
H12 = set(); x = 1
while True:
    H12.add(x); x = x * 12 % 37
    if x == 1: break
assert len(H12) == 9
cosets = []
seen37 = set()
for e in range(4):
    rep = pow(g37, e, 37)
    cs = frozenset(rep * h % 37 for h in H12)
    cosets.append(cs); seen37 |= cs
assert seen37 == set(range(1, 37))
def col_of(x37):
    for c, cs in enumerate(cosets):
        if x37 in cs: return c
    raise ValueError

nine_col = {}
for j in nines:
    x = orbs[j][0]
    nine_col[j] = col_of(x % 37)
cols = [[j for j in nines if nine_col[j] == c] for c in range(4)]
assert all(len(c) == 9 for c in cols)

def comps():
    return [k for k in itertools.product(range(10), repeat=4) if sum(k) == 18]

def canon_pair(kA, kB):
    best = None
    for r in range(4):
        a = tuple(kA[(i + r) % 4] for i in range(4))
        b = tuple(kB[(i + r) % 4] for i in range(4))
        # swap symmetry only if pa == pb handled by caller; keep unswapped here
        if best is None or (a, b) < best: best = (a, b)
    return best

def solve_branch(pa, pb, kA, kB, seconds, workers):
    m = cp_model.CpModel()
    X = [[m.NewBoolVar(f"x{s}_{j}") for j in range(len(orbs))] for s in range(2)]
    for s, pat in ((0, pa), (1, pb)):
        for mm in range(9):
            m.Add(X[s][fix_by_m[mm]] == (1 if mm in pat else 0))
    for s, kk in ((0, kA), (1, kB)):
        for c in range(4):
            m.Add(sum(X[s][j] for j in cols[c]) == kk[c])
    y = {}
    shift_seen = set()
    for d in range(1, N):
        if d in shift_seen: continue
        shift_seen.update({d * g % N for g in K})
        terms = []
        for s in range(2):
            cnt = Counter()
            for i in range(N):
                u, v = own[i], own[(i + d) % N]
                if u == v: continue
                cnt[(min(u, v), max(u, v))] += 1
            for (u, v), coef in cnt.items():
                key = (s, u, v)
                if key not in y:
                    z = m.NewBoolVar(f"y{s}_{u}_{v}")
                    m.AddBoolXOr([X[s][u], X[s][v], z.Not()])
                    y[key] = z
                terms.append(coef * y[key])
        m.Add(sum(terms) == 334)
    slv = cp_model.CpSolver()
    slv.parameters.max_time_in_seconds = seconds
    slv.parameters.num_search_workers = workers
    t0 = time.time(); st = slv.Solve(m)
    res = {"status": slv.StatusName(st), "elapsed_s": round(time.time() - t0, 2),
           "conflicts": slv.NumConflicts()}
    if st in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        seq = [[1 if slv.Value(X[s][own[i]]) else -1 for i in range(N)] for s in range(2)]
        bad = [d for d in range(1, N)
               if sum(seq[s][i] * seq[s][(i + d) % N] for s in range(2) for i in range(N)) != -2]
        res["verified_paf"] = not bad
        res["sequences"] = seq
    return res

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seconds", type=float, default=45)
    ap.add_argument("--workers", type=int, default=2)
    ap.add_argument("--survivors", default="lp333_271_split.jsonl")
    ap.add_argument("--retry", default="lp333_271_split_retry.jsonl")
    ap.add_argument("--out", default="lp333_271_deepsplit.jsonl")
    ap.add_argument("--max-subfibers", type=int, default=10**9)
    a = ap.parse_args()
    # survivors = UNKNOWN in split minus decided in retry
    decided = set()
    rp = Path(a.retry)
    if rp.exists():
        for line in rp.read_text().splitlines():
            try:
                r = json.loads(line)
                if r["status"] != "UNKNOWN":
                    decided.add((tuple(r["pa"]), tuple(r["pb"])))
            except Exception: pass
    survivors = []
    for line in Path(a.survivors).read_text().splitlines():
        try:
            r = json.loads(line)
        except Exception: continue
        if r.get("status") == "UNKNOWN" and (tuple(r["pa"]), tuple(r["pb"])) not in decided:
            survivors.append((r["i"], r["pa"], r["pb"]))
    out = Path(a.out); done = set()
    if out.exists():
        for line in out.read_text().splitlines():
            try:
                r = json.loads(line)
                done.add((tuple(r["pa"]), tuple(r["pb"]), tuple(r["kA"]), tuple(r["kB"])))
            except Exception: pass
    CS = comps()
    print(json.dumps({"event": "plan", "survivors": len(survivors),
                      "compositions": len(CS)}), flush=True)
    for si, (i, pa, pb) in enumerate(survivors[:a.max_subfibers]):
        branch_seen = set(); nbr = 0; unk = 0
        for kA in CS:
            for kB in CS:
                c = canon_pair(kA, kB)
                if c in branch_seen: continue
                branch_seen.add(c)
                if (tuple(pa), tuple(pb), tuple(c[0]), tuple(c[1])) in done: continue
                r = solve_branch(pa, pb, list(c[0]), list(c[1]), a.seconds, a.workers)
                nbr += 1
                rec = {"i": i, "pa": pa, "pb": pb, "kA": list(c[0]), "kB": list(c[1]),
                       **{k: v for k, v in r.items() if k != "sequences"}}
                if "sequences" in r: rec["sequences"] = r["sequences"]
                with out.open("a") as f: f.write(json.dumps(rec) + "\n")
                if r["status"] == "UNKNOWN": unk += 1
                if r.get("verified_paf"):
                    Path("lp333_271_WITNESS.json").write_text(json.dumps(rec))
                    print("WITNESS FOUND", flush=True)
                    return
        print(json.dumps({"event": "subfiber_done", "i": i, "branches": nbr,
                          "unknown": unk}), flush=True)

if __name__ == "__main__":
    main()
