//! Repeated-block cyclic GS (propus parameter) search at v=167.
//! Searches A,B,D with combined PAF(A)+2*PAF(B)+PAF(D)=0, then emits
//! the four-sequence family [A,B,B,D].
use std::{env,fs,thread};use std::sync::{Arc,Mutex};use std::sync::atomic::{AtomicBool,AtomicI64,Ordering};use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const N:usize=167;const H:usize=83;const COEF:[i32;3]=[1,2,1];
#[derive(Clone)]struct State{a:[[i8;N];3],r:[i32;H],e:i64}
impl State{fn new(a:[[i8;N];3])->Self{let mut s=Self{a,r:[0;H],e:0};s.recompute();s}fn recompute(&mut self){self.r=[0;H];for d in 1..=H{for k in 0..3{for i in 0..N{self.r[d-1]+=COEF[k]*self.a[k][i]as i32*self.a[k][(i+d)%N]as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}fn flip(&mut self,k:usize,p:usize){let old=self.a[k][p]as i32;for d in 1..=H{let z=self.a[k][(p+d)%N]as i32+self.a[k][(p+N-d)%N]as i32;let delta=COEF[k]*-2*old*z;let b=self.r[d-1]as i64;let c=b+delta as i64;self.e+=c*c-b*b;self.r[d-1]+=delta}self.a[k][p]=-self.a[k][p]}fn score(&self,w:&[i64;H],l1:bool)->i64{if l1{self.r.iter().zip(w).map(|(&x,&y)|y*x.abs()as i64).sum()}else{self.r.iter().zip(w).map(|(&x,&y)|y*(x as i64)*(x as i64)).sum()}}fn rows(&self)->[i32;3]{let mut z=[0;3];for k in 0..3{z[k]=self.a[k].iter().map(|&x|x as i32).sum()}z}}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next()as usize%n}fn unit(&mut self)->f64{(self.next()>>11)as f64/(1u64<<53)as f64}}
fn random(r:&mut Rng,rows:[i32;3])->State{let mut a=[[1i8;N];3];for k in 0..3{let neg=((N as i32-rows[k])/2)as usize;for i in 0..neg{a[k][i]=-1}for i in(1..N).rev(){let j=r.usize(i+1);a[k].swap(i,j)}}State::new(a)}
fn parse_rows(x:Option<&String>)->[i32;3]{let v=x.map(|s|s.split(',').map(|y|y.parse().unwrap()).collect::<Vec<i32>>()).unwrap_or_else(||vec![3,17,9]);if v.len()!=3||v[0]*v[0]+2*v[1]*v[1]+v[2]*v[2]!=668{panic!("rows need a^2+2b^2+d^2=668")}[v[0],v[1],v[2]]}
fn mv(s:&mut State,r:&mut Rng,u:&mut[(usize,usize);16],n:&mut usize){let k=r.usize(3);let mut p=r.usize(N);while s.a[k][p]!=1{p=r.usize(N)}let mut q=r.usize(N);while s.a[k][q]!=-1{q=r.usize(N)}u[*n]=(k,p);u[*n+1]=(k,q);s.flip(k,p);s.flip(k,q);*n+=2}
fn json(s:&State,solved:bool,elapsed:f64,moves:u64)->String{let a=s.a.iter().map(|x|format!("[{}]",x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>();let r=s.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");format!("{{\"construction\":\"cyclic Goethals-Seidel repeated-block order 167\",\"solved\":{},\"energy\":{},\"elapsed_s\":{},\"moves\":{},\"row_sums\":[{},{},{},{}],\"residual\":[{}],\"sequences\":[{},{},{},{}]}}\n",solved,s.e,elapsed,moves,s.rows()[0],s.rows()[1],s.rows()[1],s.rows()[2],r,a[0],a[1],a[1],a[2])}
fn update(s:&State,id:usize,start:Instant,atom:&AtomicI64,best:&Mutex<State>){let mut seen=atom.load(Ordering::Relaxed);while s.e<seen{match atom.compare_exchange_weak(seen,s.e,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=s.clone();let z=s.rows();let _=fs::write(format!("propus_167_{}_{}_{}_live.json",z[0],z[1],z[2]),json(s,false,start.elapsed().as_secs_f64(),0));eprintln!("best energy={} worker={} elapsed_s={:.3} rows={:?}",s.e,id,start.elapsed().as_secs_f64(),s.rows());return},Err(x)=>seen=x}}}
fn worker(id:usize,end:Instant,start:Instant,atom:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>,rows:[i32;3])->u64{let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(epoch^(id as u64+1).wrapping_mul(0x9e3779b97f4a7c15));let mut moves=0;while Instant::now()<end&&!stop.load(Ordering::Relaxed){let mut s=if rng.usize(10)==0{random(&mut rng,rows)}else{best.lock().unwrap().clone()};for _ in 0..rng.usize(60){let mut u=[(0,0);16];let mut n=0;mv(&mut s,&mut rng,&mut u,&mut n)}let mut w=[1i64;H];let mut stale=0usize;let mut local=s.e;for step in 0..350000usize{if step&8191==0&&(Instant::now()>=end||stop.load(Ordering::Relaxed)){break}let phase=step as f64/350000.0;let l1=id%4==2;let temp=(if l1{50.0}else if id%3==0{1800.0}else if id%3==1{600.0}else{180.0})*(0.0002f64).powf(phase)+0.02;let before=s.score(&w,l1);let roll=rng.usize(1000);let count=if roll<720{1}else if roll<960{2}else{3+rng.usize(3)};let mut undo=[(0usize,0usize);16];let mut used=0;if id%4==3&&count==1{let mut bu=[(0usize,0usize);16];let mut bn=0;let mut bs=i64::MAX;for _ in 0..128{let mut tu=[(0usize,0usize);16];let mut tn=0;mv(&mut s,&mut rng,&mut tu,&mut tn);let z=s.score(&w,l1);for &(k,p)in tu[..tn].iter().rev(){s.flip(k,p)}if z<bs{bs=z;bn=tn;bu[..tn].copy_from_slice(&tu[..tn])}}for &(k,p)in&bu[..bn]{s.flip(k,p);undo[used]=(k,p);used+=1}}else{for _ in 0..count{mv(&mut s,&mut rng,&mut undo,&mut used)}}moves+=1;let delta=s.score(&w,l1)-before;if delta>0&&rng.unit()>=(-(delta as f64)/temp).exp(){for &(k,p)in undo[..used].iter().rev(){s.flip(k,p)}}else if s.e<local{local=s.e;stale=0;update(&s,id,start,&atom,&best);if s.e==0{let mut check=s.clone();check.recompute();if check.e==0{*best.lock().unwrap()=check;stop.store(true,Ordering::SeqCst);break}}}else{stale+=1}if id%2==1&&stale>45000{for j in 0..H{if s.r[j]!=0{w[j]=(w[j]+1+(s.r[j].abs()/4)as i64).min(64)}}stale=0}else if stale>90000{for _ in 0..(10+rng.usize(25)){let mut u=[(0,0);16];let mut n=0;mv(&mut s,&mut rng,&mut u,&mut n)}stale=0}}}moves}
fn main(){let z:Vec<String>=env::args().collect();let secs=z.get(1).and_then(|x|x.parse().ok()).unwrap_or(900);let threads=z.get(2).and_then(|x|x.parse().ok()).unwrap_or(4);let rows=parse_rows(z.get(3));let mut rng=Rng(167);let initial=random(&mut rng,rows);eprintln!("seed energy={} rows={:?}",initial.e,rows);let start=Instant::now();let end=start+Duration::from_secs(secs);let atom=Arc::new(AtomicI64::new(initial.e));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let(a,b,c)=(atom.clone(),best.clone(),stop.clone());hs.push(thread::spawn(move||worker(id,end,start,a,b,c,rows)))}let moves=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut ans=best.lock().unwrap().clone();ans.recompute();let solved=ans.e==0;let q=ans.rows();let out=if solved{"propus_167_candidate.json".to_string()}else{format!("propus_167_{}_{}_{}_summary.json",q[0],q[1],q[2])};fs::write(&out,json(&ans,solved,start.elapsed().as_secs_f64(),moves)).unwrap();println!("result solved={} energy={} moves={} output={}",solved,ans.e,moves,out)}
