//! Exhaustive-neighborhood tabu search inside one reversal-orbit fibre of
//! BS(84,83).  Every move preserves the four row sums and all residuals mod 4.
use std::{env,fs,thread};
use std::sync::{Arc,Mutex};
use std::sync::atomic::{AtomicBool,AtomicI64,Ordering};
use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const L:[usize;4]=[84,84,83,83]; const H:usize=83;
#[derive(Clone)] struct State{a:[Vec<i8>;4],r:[i32;H],e:i64}
impl State{
 fn new(a:[Vec<i8>;4])->Self{let mut s=Self{a,r:[0;H],e:0};s.recompute();s}
 fn recompute(&mut self){self.r=[0;H];for k in 0..4{for d in 1..L[k]{for i in 0..L[k]-d{self.r[d-1]+=self.a[k][i]as i32*self.a[k][i+d]as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}
 fn flip(&mut self,k:usize,p:usize){let old=self.a[k][p]as i32;for d in 1..L[k]{let mut z=0;if p+d<L[k]{z+=self.a[k][p+d]as i32}if p>=d{z+=self.a[k][p-d]as i32}let dr=-2*old*z;let b=self.r[d-1]as i64;let c=b+dr as i64;self.e+=c*c-b*b;self.r[d-1]+=dr}self.a[k][p]=-self.a[k][p]}
 fn toggle_orbit(&mut self,k:usize,p:usize){let q=L[k]-1-p;self.flip(k,p);self.flip(k,q)}
 fn rows(&self)->[i32;4]{let mut z=[0;4];for k in 0..4{z[k]=self.a[k].iter().map(|&x|x as i32).sum()}z}
}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next()as usize%n}}
fn parse(path:&str)->Option<State>{let text=fs::read_to_string(path).ok()?;let start=text.find("\"sequences\"")?;let b=text[start..].as_bytes();let need:LIter=L.iter().sum();let mut v=Vec::with_capacity(need);let(mut i,mut n)=(0,0);while i<b.len()&&n<need{if b[i]==b'-'&&i+1<b.len()&&b[i+1]==b'1'{v.push(-1);n+=1;i+=2}else if b[i]==b'1'{v.push(1);n+=1;i+=1}else{i+=1}}if n!=need{return None}let mut off=0;let a=std::array::from_fn(|k|{let x=v[off..off+L[k]].to_vec();off+=L[k];x});Some(State::new(a))}
type LIter=usize;
fn json(s:&State,solved:bool,elapsed:f64,iters:u64)->String{let seq=s.a.iter().map(|x|format!("[{}]",x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");let r=s.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");format!("{{\"construction\":\"base sequences BS(84,83)\",\"search\":\"exhaustive reversal-orbit tabu\",\"solved\":{},\"energy\":{},\"parity_bad\":{},\"elapsed_s\":{},\"iterations\":{},\"row_sums\":{:?},\"residual\":[{}],\"sequences\":[{}]}}\n",solved,s.e,s.r.iter().filter(|&&x|x%4!=0).count(),elapsed,iters,s.rows(),r,seq)}
fn publish(s:&State,id:usize,start:Instant,atom:&AtomicI64,best:&Mutex<State>){let mut seen=atom.load(Ordering::Relaxed);while s.e<seen{match atom.compare_exchange_weak(seen,s.e,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=s.clone();let _=fs::write("bs_84_83_tabu_live.json",json(s,false,start.elapsed().as_secs_f64(),0));eprintln!("best energy={} worker={} elapsed_s={:.3}",s.e,id,start.elapsed().as_secs_f64());return},Err(x)=>seen=x}}}
fn random_move(s:&mut State,rng:&mut Rng){loop{let k=rng.usize(4);let h=L[k]/2;if rng.usize(3)<2{for _ in 0..64{let p=rng.usize(h);let q=L[k]-1-p;if s.a[k][p]!=s.a[k][q]{s.toggle_orbit(k,p);return}}}else{let mut pp=vec![];let mut mm=vec![];for p in 0..h{let z=s.a[k][p]+s.a[k][L[k]-1-p];if z==2{pp.push(p)}else if z== -2{mm.push(p)}}if !pp.is_empty()&&!mm.is_empty(){let p=pp[rng.usize(pp.len())];let q=mm[rng.usize(mm.len())];s.toggle_orbit(k,p);s.toggle_orbit(k,q);return}}}}
fn worker(id:usize,end:Instant,start:Instant,atom:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>)->u64{
 let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(epoch^(id as u64+31).wrapping_mul(0x9e3779b97f4a7c15));let mut s=best.lock().unwrap().clone();let mut tabu=[[0u64;42];4];let mut iter=0u64;let mut stale=0u64;
 while Instant::now()<end&&!stop.load(Ordering::Relaxed){let global=atom.load(Ordering::Relaxed);let mut pick=(i64::MAX,0usize,0usize,usize::MAX);let mut ties=0usize;
  for k in 0..4{let h=L[k]/2;let mut pp=vec![];let mut mm=vec![];for p in 0..h{let q=L[k]-1-p;if s.a[k][p]!=s.a[k][q]{let old=s.e;s.toggle_orbit(k,p);let de=s.e-old;s.toggle_orbit(k,p);let aspir=old+de<global;if aspir||tabu[k][p]<=iter{if de<pick.0{pick=(de,k,p,usize::MAX);ties=1}else if de==pick.0{ties+=1;if rng.usize(ties)==0{pick=(de,k,p,usize::MAX)}}}}else if s.a[k][p]==1{pp.push(p)}else{mm.push(p)}}for &p in &pp{for &q in &mm{let old=s.e;s.toggle_orbit(k,p);s.toggle_orbit(k,q);let de=s.e-old;s.toggle_orbit(k,q);s.toggle_orbit(k,p);let aspir=old+de<global;if aspir||(tabu[k][p]<=iter&&tabu[k][q]<=iter){if de<pick.0{pick=(de,k,p,q);ties=1}else if de==pick.0{ties+=1;if rng.usize(ties)==0{pick=(de,k,p,q)}}}}}}
  if pick.0==i64::MAX{tabu=[[0u64;42];4];continue}s.toggle_orbit(pick.1,pick.2);if pick.3!=usize::MAX{s.toggle_orbit(pick.1,pick.3)}iter+=1;stale+=1;let tenure=7+rng.usize(17)as u64+(stale/1500).min(30);tabu[pick.1][pick.2]=iter+tenure;if pick.3!=usize::MAX{tabu[pick.1][pick.3]=iter+tenure}if s.e<global{publish(&s,id,start,&atom,&best);stale=0;if s.e==0{let mut chk=s.clone();chk.recompute();if chk.e==0{*best.lock().unwrap()=chk;stop.store(true,Ordering::SeqCst);break}}}if stale>5000{s=best.lock().unwrap().clone();for _ in 0..(6+rng.usize(20)){random_move(&mut s,&mut rng)}tabu=[[0u64;42];4];stale=0}}
 iter
}
fn main(){let z:Vec<String>=env::args().collect();let secs=z.get(1).and_then(|x|x.parse().ok()).unwrap_or(900);let threads=z.get(2).and_then(|x|x.parse().ok()).unwrap_or(4);let initial=z.get(3).and_then(|p|parse(p)).expect("checkpoint JSON required");assert_eq!(initial.rows().iter().map(|x|x*x).sum::<i32>(),334);assert!(initial.r.iter().all(|x|x%4==0));eprintln!("seed energy={} rows={:?}",initial.e,initial.rows());let start=Instant::now();let end=start+Duration::from_secs(secs);let atom=Arc::new(AtomicI64::new(initial.e));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let(a,b,c)=(atom.clone(),best.clone(),stop.clone());hs.push(thread::spawn(move||worker(id,end,start,a,b,c)))}let iters=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut ans=best.lock().unwrap().clone();ans.recompute();let solved=ans.e==0;let out=if solved{"bs_84_83_candidate.json"}else{"bs_84_83_tabu_summary.json"};fs::write(out,json(&ans,solved,start.elapsed().as_secs_f64(),iters)).unwrap();println!("result solved={} energy={} iterations={} output={}",solved,ans.e,iters,out)}
