//! Native search for a cyclic Goethals--Seidel difference family on Z_167.
//! Four length-167 sequences with zero summed periodic autocorrelation give
//! a Hadamard matrix of order 668.  Row sums are held fixed by sign swaps.
use std::{env,fs,thread};
use std::sync::{Arc,Mutex,OnceLock};
use std::sync::atomic::{AtomicBool,AtomicI64,Ordering};
use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const N:usize=167;const H:usize=83;
static ACTIVE:OnceLock<usize>=OnceLock::new();fn active()->usize{*ACTIVE.get().unwrap_or(&4)}
#[derive(Clone)]struct State{a:[[i8;N];4],r:[i32;H],e:i64}
impl State{
 fn new(a:[[i8;N];4])->Self{let mut s=Self{a,r:[0;H],e:0};s.recompute();s}
 fn recompute(&mut self){self.r=[0;H];for d in 1..=H{for k in 0..4{for i in 0..N{self.r[d-1]+=self.a[k][i]as i32*self.a[k][(i+d)%N]as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}
 fn flip(&mut self,k:usize,p:usize){let old=self.a[k][p]as i32;for d in 1..=H{let z=self.a[k][(p+d)%N]as i32+self.a[k][(p+N-d)%N]as i32;let delta=-2*old*z;let b=self.r[d-1]as i64;let c=b+delta as i64;self.e+=c*c-b*b;self.r[d-1]+=delta}self.a[k][p]=-self.a[k][p]}
 fn score(&self,w:&[i64;H],l1:bool)->i64{if l1{self.r.iter().zip(w).map(|(&x,&y)|y*x.abs()as i64).sum()}else{self.r.iter().zip(w).map(|(&x,&y)|y*(x as i64)*(x as i64)).sum()}}
 fn rows(&self)->[i32;4]{let mut z=[0;4];for k in 0..4{z[k]=self.a[k].iter().map(|&x|x as i32).sum()}z}
}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next()as usize%n}fn unit(&mut self)->f64{(self.next()>>11)as f64/(1u64<<53)as f64}}
fn parse(path:&str)->Option<State>{let text=fs::read_to_string(path).ok()?;let start=text.find("\"sequences\"")?;let b=text[start..].as_bytes();let mut v=Vec::with_capacity(668);let(mut i,mut n)=(0,0);while i<b.len()&&n<668{if b[i]==b'-'&&i+1<b.len()&&b[i+1]==b'1'{v.push(-1);n+=1;i+=2}else if b[i]==b'1'{v.push(1);n+=1;i+=1}else{i+=1}}if n!=668{return None}let mut a=[[1i8;N];4];for k in 0..4{a[k].copy_from_slice(&v[k*N..(k+1)*N])}Some(State::new(a))}
fn random(r:&mut Rng,rows:[i32;4])->State{let mut a=[[1i8;N];4];for k in 0..4{let neg=((N as i32-rows[k])/2)as usize;for i in 0..neg{a[k][i]=-1}for i in (1..N).rev(){let j=r.usize(i+1);a[k].swap(i,j)}}State::new(a)}
fn swap_move(s:&mut State,r:&mut Rng,u:&mut[(usize,usize);24],n:&mut usize){let k=r.usize(active());let mut p=r.usize(N);while s.a[k][p]!=1{p=r.usize(N)}let mut q=r.usize(N);while s.a[k][q]!=-1{q=r.usize(N)}u[*n]=(k,p);u[*n+1]=(k,q);s.flip(k,p);s.flip(k,q);*n+=2}
fn json(s:&State,solved:bool,elapsed:f64,moves:u64)->String{let seq=s.a.iter().map(|x|format!("[{}]",x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");let r=s.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");format!("{{\"construction\":\"cyclic Goethals-Seidel order 167\",\"solved\":{},\"energy\":{},\"elapsed_s\":{},\"moves\":{},\"row_sums\":{:?},\"residual\":[{}],\"sequences\":[{}]}}\n",solved,s.e,elapsed,moves,s.rows(),r,seq)}
fn update(s:&State,id:usize,start:Instant,atom:&AtomicI64,best:&Mutex<State>){let mut seen=atom.load(Ordering::Relaxed);while s.e<seen{match atom.compare_exchange_weak(seen,s.e,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=s.clone();let r=s.rows();let _=fs::write(format!("gs_167_native_{}_{}_{}_{}_live.json",r[0],r[1],r[2],r[3]),json(s,false,start.elapsed().as_secs_f64(),0));eprintln!("best energy={} worker={} elapsed_s={:.3} rows={:?}",s.e,id,start.elapsed().as_secs_f64(),s.rows());return},Err(x)=>seen=x}}}
fn worker(id:usize,end:Instant,start:Instant,atom:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>)->u64{let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(epoch^(id as u64+1).wrapping_mul(0x9e3779b97f4a7c15));let mut moves=0;while Instant::now()<end&&!stop.load(Ordering::Relaxed){let base=best.lock().unwrap().clone();let rows=base.rows();let mut s=if rng.usize(10)==0{let mut z=random(&mut rng,rows);for k in active()..4{z.a[k]=base.a[k]}z.recompute();z}else{base};for _ in 0..rng.usize(80){let mut u=[(0,0);24];let mut n=0;swap_move(&mut s,&mut rng,&mut u,&mut n)}let mut w=[1i64;H];let mut stale=0usize;let mut local=s.e;for step in 0..400000usize{if step&8191==0&&(Instant::now()>=end||stop.load(Ordering::Relaxed)){break}let phase=step as f64/400000.0;let l1=id%4==2;let temp=(if l1{40.0}else if id%3==0{1800.0}else if id%3==1{600.0}else{180.0})*(0.0002f64).powf(phase)+0.02;let before=s.score(&w,l1);let roll=rng.usize(1000);let count=if roll<700{1}else if roll<950{2}else{3+rng.usize(3)};let mut undo=[(0usize,0usize);24];let mut used=0;if id%4==3&&count==1{let mut bu=[(0usize,0usize);24];let mut bn=0;let mut bs=i64::MAX;for _ in 0..128{let mut tu=[(0usize,0usize);24];let mut tn=0;swap_move(&mut s,&mut rng,&mut tu,&mut tn);let z=s.score(&w,l1);for &(k,p) in tu[..tn].iter().rev(){s.flip(k,p)}if z<bs{bs=z;bn=tn;bu[..tn].copy_from_slice(&tu[..tn])}}for &(k,p) in &bu[..bn]{s.flip(k,p);undo[used]=(k,p);used+=1}}else{for _ in 0..count{swap_move(&mut s,&mut rng,&mut undo,&mut used)}}moves+=1;let delta=s.score(&w,l1)-before;if delta>0&&rng.unit()>=(-(delta as f64)/temp).exp(){for &(k,p) in undo[..used].iter().rev(){s.flip(k,p)}}else if s.e<local{local=s.e;stale=0;update(&s,id,start,&atom,&best);if s.e==0{let mut check=s.clone();check.recompute();if check.e==0{*best.lock().unwrap()=check;stop.store(true,Ordering::SeqCst);break}}}else{stale+=1}if id%2==1&&stale>50000{for j in 0..H{if s.r[j]!=0{w[j]=(w[j]+1+(s.r[j].abs()/4)as i64).min(64)}}stale=0}else if stale>100000{for _ in 0..(10+rng.usize(30)){let mut u=[(0,0);24];let mut n=0;swap_move(&mut s,&mut rng,&mut u,&mut n)}stale=0}}}moves}
fn main(){let z:Vec<String>=env::args().collect();let secs=z.get(1).and_then(|x|x.parse().ok()).unwrap_or(900);let threads=z.get(2).and_then(|x|x.parse().ok()).unwrap_or(4);let active_count=z.get(4).and_then(|x|x.parse().ok()).unwrap_or(4);assert!((1..=4).contains(&active_count));ACTIVE.set(active_count).unwrap();let mut rng=Rng(167);let initial=z.get(3).and_then(|p|parse(p)).unwrap_or_else(||random(&mut rng,[15,15,13,7]));assert_eq!(initial.rows().iter().map(|x|x*x).sum::<i32>(),668);eprintln!("seed energy={} rows={:?} active={}",initial.e,initial.rows(),active());let start=Instant::now();let end=start+Duration::from_secs(secs);let atom=Arc::new(AtomicI64::new(initial.e));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let(a,b,c)=(atom.clone(),best.clone(),stop.clone());hs.push(thread::spawn(move||worker(id,end,start,a,b,c)))}let moves=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut ans=best.lock().unwrap().clone();ans.recompute();let solved=ans.e==0;let r=ans.rows();let out=if solved{"gs_167_candidate.json".to_string()}else{format!("gs_167_native_{}_{}_{}_{}_summary.json",r[0],r[1],r[2],r[3])};fs::write(&out,json(&ans,solved,start.elapsed().as_secs_f64(),moves)).unwrap();println!("result solved={} energy={} moves={} output={}",solved,ans.e,moves,out)}
