//! Product-theorem fiber for good matrices of order 167.
//! A is skew, B/C/D symmetric, rows are [1,-9,15,19], and
//! a_k b_k c_k d_k = -a_(2k) (k != 0) is maintained identically.
use std::{env,fs,thread};use std::sync::{Arc,Mutex};use std::sync::atomic::{AtomicBool,AtomicI64,Ordering};use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const N:usize=167;const H:usize=83;const INV2:usize=84;
#[derive(Clone)]struct State{a:[[i8;N];4],r:[i32;H],e:i64}
impl State{fn new(a:[[i8;N];4])->Self{let mut s=Self{a,r:[0;H],e:0};s.recompute();s}fn recompute(&mut self){self.r=[0;H];for d in 1..=H{for k in 0..4{for i in 0..N{self.r[d-1]+=self.a[k][i]as i32*self.a[k][(i+d)%N]as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}fn flip(&mut self,k:usize,p:usize){let old=self.a[k][p]as i32;for d in 1..=H{let z=self.a[k][(p+d)%N]as i32+self.a[k][(p+N-d)%N]as i32;let delta=-2*old*z;let b=self.r[d-1]as i64;let c=b+delta as i64;self.e+=c*c-b*b;self.r[d-1]+=delta}self.a[k][p]=-self.a[k][p]}fn score(&self,w:&[i64;H],l1:bool)->i64{if l1{self.r.iter().zip(w).map(|(&x,&y)|y*x.abs()as i64).sum()}else{self.r.iter().zip(w).map(|(&x,&y)|y*(x as i64)*(x as i64)).sum()}}fn rows(&self)->[i32;4]{let mut z=[0;4];for k in 0..4{z[k]=self.a[k].iter().map(|&x|x as i32).sum()}z}fn valid(&self)->bool{self.rows()==[1,-9,15,19]&&(1..N).all(|k|self.a[0][k]*self.a[1][k]*self.a[2][k]*self.a[3][k]==-self.a[0][2*k%N])&&(1..N).all(|k|self.a[0][k]==-self.a[0][N-k]&&(1..4).all(|j|self.a[j][k]==self.a[j][N-k]))}}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next()as usize%n}fn unit(&mut self)->f64{(self.next()>>11)as f64/(1u64<<53)as f64}}
fn shuffle(x:&mut[i8],r:&mut Rng){for i in(1..x.len()).rev(){let j=r.usize(i+1);x.swap(i,j)}}
fn symmetric(r:&mut Rng,row:i32)->[i8;N]{let mut x=[1i8;N];x[0]=1;assert_eq!(row.rem_euclid(4),3);let sum=(row-1)/2;let neg=((H as i32-sum)/2)as usize;let mut g=[1i8;H];for z in&mut g[..neg]{*z=-1}shuffle(&mut g,r);for i in 1..=H{x[i]=g[i-1];x[N-i]=g[i-1]}x}
fn random_state(r:&mut Rng)->State{loop{let mut a=[[1i8;N];4];a[0][0]=1;for g in 1..=H{let x=if r.next()&1==0{1}else{-1};a[0][g]=x;a[0][N-g]=-x}a[1]=symmetric(r,-9);a[2]=symmetric(r,15);a[3][0]=1;for k in 1..N{a[3][k]=-a[0][k]*a[0][2*k%N]*a[1][k]*a[2][k]}let s=State::new(a);if s.rows()[3]==19{assert!(s.valid());return s}}}
fn flip_ind(s:&mut State,k:usize,p:usize){s.flip(k,p);if k==0{s.flip(3,p);let h=p*INV2%N;if h!=p{s.flip(3,h)}}else{s.flip(3,p)}}
#[derive(Clone,Copy)]struct Move{kind:usize,p:usize,q:usize}
fn apply(s:&mut State,m:Move){if m.kind==0{flip_ind(s,0,m.p);flip_ind(s,0,N-m.p)}else{for g in[m.p,m.q]{flip_ind(s,m.kind,g);flip_ind(s,m.kind,N-g)}}}
fn choose(s:&State,r:&mut Rng)->Move{for _ in 0..256{let k=r.usize(3);if k==0{let p=1+r.usize(H);let h=p*INV2%N;if s.a[3][p]==-s.a[3][h]{return Move{kind:0,p,q:0}}}else{let p=1+r.usize(H);let q=1+r.usize(H);if p!=q&&s.a[k][p]==-s.a[k][q]&&s.a[3][p]==-s.a[3][q]{return Move{kind:k,p,q}}}}panic!("no row-preserving product move found")}
fn json(s:&State,solved:bool,elapsed:f64,moves:u64)->String{let seq=s.a.iter().map(|x|format!("[{}]",x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");let r=s.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");format!("{{\"construction\":\"cyclic Goethals-Seidel good product fiber order 167\",\"solved\":{},\"energy\":{},\"elapsed_s\":{},\"moves\":{},\"row_sums\":{:?},\"product_theorem\":true,\"residual\":[{}],\"sequences\":[{}]}}\n",solved,s.e,elapsed,moves,s.rows(),r,seq)}
fn update(s:&State,id:usize,start:Instant,atom:&AtomicI64,best:&Mutex<State>){let mut seen=atom.load(Ordering::Relaxed);while s.e<seen{match atom.compare_exchange_weak(seen,s.e,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=s.clone();let _=fs::write("good_product_167_live.json",json(s,false,start.elapsed().as_secs_f64(),0));eprintln!("best energy={} worker={} elapsed_s={:.3}",s.e,id,start.elapsed().as_secs_f64());return},Err(x)=>seen=x}}}
fn worker(id:usize,end:Instant,start:Instant,atom:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>)->u64{let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(epoch^(id as u64+1).wrapping_mul(0x9e3779b97f4a7c15));let mut moves=0;while Instant::now()<end&&!stop.load(Ordering::Relaxed){let mut s=if rng.usize(10)==0{random_state(&mut rng)}else{best.lock().unwrap().clone()};for _ in 0..rng.usize(40){let m=choose(&s,&mut rng);apply(&mut s,m)}let mut w=[1i64;H];let mut stale=0usize;let mut local=s.e;for step in 0..300000usize{if step&8191==0&&(Instant::now()>=end||stop.load(Ordering::Relaxed)){break}let phase=step as f64/300000.0;let l1=id%4==2;let temp=(if l1{60.0}else if id%3==0{1800.0}else if id%3==1{600.0}else{180.0})*(0.0002f64).powf(phase)+0.02;let before=s.score(&w,l1);let roll=rng.usize(1000);let count=if roll<720{1}else if roll<960{2}else{3+rng.usize(3)};let mut undo=[Move{kind:0,p:0,q:0};8];let mut used=0;if id%4==3&&count==1{let mut bm=Move{kind:0,p:1,q:0};let mut bs=i64::MAX;for _ in 0..128{let m=choose(&s,&mut rng);apply(&mut s,m);let z=s.score(&w,l1);apply(&mut s,m);if z<bs{bs=z;bm=m}}apply(&mut s,bm);undo[0]=bm;used=1}else{for _ in 0..count{let m=choose(&s,&mut rng);apply(&mut s,m);undo[used]=m;used+=1}}moves+=1;let delta=s.score(&w,l1)-before;if delta>0&&rng.unit()>=(-(delta as f64)/temp).exp(){for &m in undo[..used].iter().rev(){apply(&mut s,m)}}else if s.e<local{local=s.e;stale=0;update(&s,id,start,&atom,&best);if s.e==0{let mut check=s.clone();check.recompute();if check.e==0&&check.valid(){*best.lock().unwrap()=check;stop.store(true,Ordering::SeqCst);break}}}else{stale+=1}if id%2==1&&stale>40000{for j in 0..H{if s.r[j]!=0{w[j]=(w[j]+1+(s.r[j].abs()/4)as i64).min(64)}}stale=0}else if stale>80000{for _ in 0..(8+rng.usize(20)){let m=choose(&s,&mut rng);apply(&mut s,m)}stale=0}}}moves}
fn main(){let z:Vec<String>=env::args().collect();let secs=z.get(1).and_then(|x|x.parse().ok()).unwrap_or(900);let threads=z.get(2).and_then(|x|x.parse().ok()).unwrap_or(4);let mut rng=Rng(167668);let initial=random_state(&mut rng);eprintln!("seed energy={} rows={:?}",initial.e,initial.rows());let start=Instant::now();let end=start+Duration::from_secs(secs);let atom=Arc::new(AtomicI64::new(initial.e));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let(a,b,c)=(atom.clone(),best.clone(),stop.clone());hs.push(thread::spawn(move||worker(id,end,start,a,b,c)))}let moves=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut ans=best.lock().unwrap().clone();ans.recompute();assert!(ans.valid());let solved=ans.e==0;let out=if solved{"good_product_167_candidate.json"}else{"good_product_167_summary.json"};fs::write(out,json(&ans,solved,start.elapsed().as_secs_f64(),moves)).unwrap();println!("result solved={} energy={} moves={} output={}",solved,ans.e,moves,out)}
