//! Native exact-integer search for a length-9 compression of LP(333).
use std::{env,fs,thread};use std::sync::{Arc,Mutex};use std::sync::atomic::{AtomicBool,AtomicI64,Ordering};use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const N:usize=9;
#[derive(Clone)]struct State{c:[[i32;N];2],r:[i32;5],e:i64}
impl State{fn recompute(&mut self){self.r[0]=self.c.iter().flatten().map(|x|x*x).sum::<i32>()-594;for h in 1..=4{self.r[h]=74+(0..2).map(|s|(0..N).map(|i|self.c[s][i]*self.c[s][(i+h)%N]).sum::<i32>()).sum::<i32>()}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}fn sums(&self)->[i32;2]{[self.c[0].iter().sum(),self.c[1].iter().sum()]}}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next()as usize%n}fn unit(&mut self)->f64{(self.next()>>11)as f64/(1u64<<53)as f64}}
fn random(r:&mut Rng)->State{let vals=[-11,-9,-7,-5,-3,-1,1,3,5,7,9,11];loop{let mut c=[[1i32;N];2];for s in 0..2{let mut sum=0;for i in 0..N-1{c[s][i]=vals[r.usize(vals.len())];sum+=c[s][i]}c[s][N-1]=1-sum;if c[s][N-1]< -37||c[s][N-1]>37||c[s][N-1]%2==0{continue}}let mut z=State{c,r:[0;5],e:0};if z.sums()==[1,1]{z.recompute();return z}}}
fn json(z:&State,solved:bool,t:f64,m:u64)->String{format!("{{\"construction\":\"LP(333) exact length-9 compression\",\"solved\":{},\"energy\":{},\"elapsed_s\":{},\"moves\":{},\"sums\":{:?},\"residual\":{:?},\"compressed_sequences\":{:?},\"column_plus_counts\":{:?}}}\n",solved,z.e,t,m,z.sums(),z.r,z.c,z.c.map(|x|x.map(|v|(v+37)/2)))}
fn publish(z:&State,id:usize,start:Instant,atom:&AtomicI64,best:&Mutex<State>){let mut seen=atom.load(Ordering::Relaxed);while z.e<seen{match atom.compare_exchange_weak(seen,z.e,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=z.clone();let _=fs::write("legendre9_native_live.json",json(z,false,start.elapsed().as_secs_f64(),0));eprintln!("best energy={} worker={} residual={:?} elapsed_s={:.3}",z.e,id,z.r,start.elapsed().as_secs_f64());return},Err(x)=>seen=x}}}
fn worker(id:usize,end:Instant,start:Instant,atom:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>)->u64{let ep=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(ep^(id as u64+151).wrapping_mul(0x9e3779b97f4a7c15));let mut moves=0;while Instant::now()<end&&!stop.load(Ordering::Relaxed){let mut z=if rng.usize(4)==0{random(&mut rng)}else{best.lock().unwrap().clone()};for step in 0..500000{if step&8191==0&&(Instant::now()>=end||stop.load(Ordering::Relaxed)){break}let phase=step as f64/500000.;let temp=(if id%3==0{50000.}else if id%3==1{10000.}else{2500.})*(0.0001f64).powf(phase)+0.01;let old=z.clone();let count=if rng.usize(10)<8{1}else{2+rng.usize(3)};for _ in 0..count{let s=rng.usize(2);let i=rng.usize(N);let mut j=rng.usize(N-1);if j>=i{j+=1}let dir=if rng.usize(2)==0{2}else{-2};if z.c[s][i]+dir>=-37&&z.c[s][i]+dir<=37&&z.c[s][j]-dir>=-37&&z.c[s][j]-dir<=37{z.c[s][i]+=dir;z.c[s][j]-=dir}}z.recompute();moves+=1;let de=z.e-old.e;if de>0&&rng.unit()>=(-(de as f64)/temp).exp(){z=old}else if z.e<atom.load(Ordering::Relaxed){publish(&z,id,start,&atom,&best);if z.e==0{stop.store(true,Ordering::SeqCst);break}}}}moves}
fn main(){let a:Vec<String>=env::args().collect();let secs=a.get(1).and_then(|x|x.parse().ok()).unwrap_or(600);let threads=a.get(2).and_then(|x|x.parse().ok()).unwrap_or(1);let seed=a.get(4).and_then(|x|x.parse().ok()).unwrap_or(9);let mut rng=Rng(seed);let initial=random(&mut rng);let start=Instant::now();let end=start+Duration::from_secs(secs);let atom=Arc::new(AtomicI64::new(initial.e));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let(x,y,z)=(atom.clone(),best.clone(),stop.clone());hs.push(thread::spawn(move||worker(id,end,start,x,y,z)))}let moves=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut ans=best.lock().unwrap().clone();ans.recompute();let solved=ans.e==0;let out=a.get(3).map(String::as_str).unwrap_or(if solved{"legendre9_native_candidate.json"}else{"legendre9_native_summary.json"});fs::write(out,json(&ans,solved,start.elapsed().as_secs_f64(),moves)).unwrap();println!("result solved={} energy={} output={}",solved,ans.e,out)}
