//! Native search for a binary Legendre pair of length 333 with the exact
//! quadratic-character 37-compression fixed.  Swaps occur within residue
//! classes modulo 37 and therefore preserve the compression exactly.
use std::{env,fs,thread};
use std::sync::{Arc,Mutex};
use std::sync::atomic::{AtomicBool,AtomicI64,Ordering};
use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const N:usize=333;const H:usize=166;const P:usize=37;const Q:usize=9;
#[derive(Clone)]struct State{a:[[i8;N];2],r:[i32;H],e:i64}
impl State{
 fn new(a:[[i8;N];2])->Self{let mut s=Self{a,r:[0;H],e:0};s.recompute();s}
 fn recompute(&mut self){self.r=[2;H];for d in 1..=H{for s in 0..2{for i in 0..N{self.r[d-1]+=self.a[s][i]as i32*self.a[s][(i+d)%N]as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}
 fn flip(&mut self,s:usize,p:usize){let old=self.a[s][p]as i32;for d in 1..=H{let z=self.a[s][(p+d)%N]as i32+self.a[s][(p+N-d)%N]as i32;let dr=-2*old*z;let b=self.r[d-1]as i64;let c=b+dr as i64;self.e+=c*c-b*b;self.r[d-1]+=dr}self.a[s][p]=-self.a[s][p]}
 fn score(&self,w:&[i64;H],l1:bool)->i64{if l1{self.r.iter().zip(w).map(|(&x,&y)|y*x.abs()as i64).sum()}else{self.r.iter().zip(w).map(|(&x,&y)|y*(x as i64)*(x as i64)).sum()}}
 fn sums(&self)->[i32;2]{[self.a[0].iter().map(|&x|x as i32).sum(),self.a[1].iter().map(|&x|x as i32).sum()]}
}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next()as usize%n}fn unit(&mut self)->f64{(self.next()>>11)as f64/(1u64<<53)as f64}}
fn chi(x:usize)->i32{if x==0{0}else if (1..P).any(|y|(y*y)%P==x){1}else{-1}}
fn target(s:usize,r:usize)->i32{if r==0{1}else if s==0{3*chi(r)}else{-3*chi(r)}}
fn random(rng:&mut Rng)->State{let mut a=[[1i8;N];2];for s in 0..2{for r in 0..P{let neg=((Q as i32-target(s,r))/2)as usize;let mut ks=(0..Q).collect::<Vec<_>>();for i in (1..Q).rev(){let j=rng.usize(i+1);ks.swap(i,j)}for &k in &ks[..neg]{a[s][r+P*k]=-1}}}State::new(a)}
fn swap_move(st:&mut State,rng:&mut Rng,u:&mut[(usize,usize);24],n:&mut usize){let s=rng.usize(2);let r=rng.usize(P);let mut kp=rng.usize(Q);while st.a[s][r+P*kp]!=1{kp=rng.usize(Q)}let mut km=rng.usize(Q);while st.a[s][r+P*km]!=-1{km=rng.usize(Q)}let p=r+P*kp;let q=r+P*km;u[*n]=(s,p);u[*n+1]=(s,q);st.flip(s,p);st.flip(s,q);*n+=2}
fn rotate_move(st:&mut State,rng:&mut Rng,u:&mut[(usize,usize);24],n:&mut usize){let s=rng.usize(2);let r=rng.usize(P);let sh=1+rng.usize(Q-1);let old=std::array::from_fn::<i8,Q,_>(|k|st.a[s][r+P*k]);for k in 0..Q{if old[k]!=old[(k+sh)%Q]{let p=r+P*k;u[*n]=(s,p);st.flip(s,p);*n+=1}}}
fn compression(st:&State)->[[i32;P];2]{std::array::from_fn(|s|std::array::from_fn(|r|(0..Q).map(|k|st.a[s][r+P*k]as i32).sum()))}
fn json(st:&State,solved:bool,elapsed:f64,moves:u64)->String{let seq=st.a.iter().map(|x|format!("[{}]",x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");let rr=st.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");let cc=compression(st);format!("{{\"construction\":\"Legendre pair length 333\",\"fixed_compression\":\"quadratic-character length 37\",\"solved\":{},\"energy\":{},\"elapsed_s\":{},\"moves\":{},\"sums\":{:?},\"residual_paf_plus_2\":[{}],\"compression37\":{:?},\"sequences\":[{}]}}\n",solved,st.e,elapsed,moves,st.sums(),rr,cc,seq)}
fn publish(st:&State,id:usize,start:Instant,atom:&AtomicI64,best:&Mutex<State>){let mut seen=atom.load(Ordering::Relaxed);while st.e<seen{match atom.compare_exchange_weak(seen,st.e,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=st.clone();let _=fs::write("lp333_native_live.json",json(st,false,start.elapsed().as_secs_f64(),0));eprintln!("best energy={} worker={} elapsed_s={:.3}",st.e,id,start.elapsed().as_secs_f64());return},Err(x)=>seen=x}}}
fn worker(id:usize,end:Instant,start:Instant,atom:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>)->u64{let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(epoch^(id as u64+101).wrapping_mul(0x9e3779b97f4a7c15));let mut moves=0u64;while Instant::now()<end&&!stop.load(Ordering::Relaxed){let mut st=if rng.usize(8)==0{random(&mut rng)}else{best.lock().unwrap().clone()};for _ in 0..rng.usize(100){let mut u=[(0,0);24];let mut n=0;swap_move(&mut st,&mut rng,&mut u,&mut n)}let mut w=[1i64;H];let mut stale=0usize;let mut local=st.e;for step in 0..500000usize{if step&8191==0&&(Instant::now()>=end||stop.load(Ordering::Relaxed)){break}let phase=step as f64/500000.0;let l1=id%4==2;let temp=(if l1{90.0}else if id%3==0{3500.0}else if id%3==1{1000.0}else{300.0})*(0.0002f64).powf(phase)+0.03;let before=st.score(&w,l1);let roll=rng.usize(1000);let count=if roll<620{1}else if roll<900{2}else if roll<980{3}else{4+rng.usize(3)};let mut undo=[(0usize,0usize);24];let mut used=0;if roll>=960{rotate_move(&mut st,&mut rng,&mut undo,&mut used)}else if id%5==4&&count==1{let mut bu=[(0usize,0usize);24];let mut bn=0;let mut bs=i64::MAX;for _ in 0..256{let mut tu=[(0usize,0usize);24];let mut tn=0;swap_move(&mut st,&mut rng,&mut tu,&mut tn);let z=st.score(&w,l1);for &(s,p) in tu[..tn].iter().rev(){st.flip(s,p)}if z<bs{bs=z;bn=tn;bu[..tn].copy_from_slice(&tu[..tn])}}for &(s,p) in &bu[..bn]{st.flip(s,p);undo[used]=(s,p);used+=1}}else{for _ in 0..count{swap_move(&mut st,&mut rng,&mut undo,&mut used)}}moves+=1;let de=st.score(&w,l1)-before;if de>0&&rng.unit()>=(-(de as f64)/temp).exp(){for &(s,p) in undo[..used].iter().rev(){st.flip(s,p)}}else if st.e<local{local=st.e;stale=0;publish(&st,id,start,&atom,&best);if st.e==0{let mut chk=st.clone();chk.recompute();if chk.e==0{*best.lock().unwrap()=chk;stop.store(true,Ordering::SeqCst);break}}}else{stale+=1}if id%2==1&&stale>50000{for j in 0..H{if st.r[j]!=0{w[j]=(w[j]+1+(st.r[j].abs()/4)as i64).min(64)}}stale=0}else if stale>120000{break}}}moves}

fn load_json(path:&str)->Option<State>{let t=fs::read_to_string(path).ok()?;let p=t.find("\"sequences\"")?;let v:Vec<i8>=t[p..].split(|c:char|!(c=='-'||c.is_ascii_digit())).filter(|x|!x.is_empty()).take(2*N).map(|x|x.parse()).collect::<Result<_,_>>().ok()?;if v.len()!=2*N{return None}let mut z=[[0i8;N];2];for s in 0..2{z[s].copy_from_slice(&v[s*N..(s+1)*N])}Some(State::new(z))}
fn main(){let z:Vec<String>=env::args().collect();let secs=z.get(1).and_then(|x|x.parse().ok()).unwrap_or(1800);let threads=z.get(2).and_then(|x|x.parse().ok()).unwrap_or(4);let mut rng=Rng(333);let initial=z.get(3).and_then(|p|load_json(p)).unwrap_or_else(||random(&mut rng));assert_eq!(initial.sums(),[1,1]);for s in 0..2{for r in 0..P{assert_eq!(compression(&initial)[s][r],target(s,r))}}eprintln!("seed energy={} sums={:?}",initial.e,initial.sums());let start=Instant::now();let end=start+Duration::from_secs(secs);let atom=Arc::new(AtomicI64::new(initial.e));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let(a,b,c)=(atom.clone(),best.clone(),stop.clone());hs.push(thread::spawn(move||worker(id,end,start,a,b,c)))}let moves=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut ans=best.lock().unwrap().clone();ans.recompute();let solved=ans.e==0;let out=z.get(4).cloned().unwrap_or_else(||if solved{"lp333_candidate.json".into()}else{"lp333_native_rotate_summary.json".into()});fs::write(&out,json(&ans,solved,start.elapsed().as_secs_f64(),moves)).unwrap();println!("result solved={} energy={} moves={} output={}",solved,ans.e,moves,out)}
