//! Search for good matrices of order 167: one skew and three symmetric
//! circulant sequences whose summed periodic autocorrelation vanishes.
use std::{env,fs,thread};use std::sync::{Arc,Mutex};use std::sync::atomic::{AtomicBool,AtomicI64,Ordering};use std::time::{Duration,Instant,SystemTime,UNIX_EPOCH};
const N:usize=167;const H:usize=83;
#[derive(Clone)]struct State{a:[[i8;N];4],r:[i32;H],e:i64}
impl State{fn new(a:[[i8;N];4])->Self{let mut s=Self{a,r:[0;H],e:0};s.recompute();s}fn recompute(&mut self){self.r=[0;H];for d in 1..=H{for k in 0..4{for i in 0..N{self.r[d-1]+=self.a[k][i]as i32*self.a[k][(i+d)%N]as i32}}}self.e=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}fn flip(&mut self,k:usize,p:usize){let old=self.a[k][p]as i32;for d in 1..=H{let z=self.a[k][(p+d)%N]as i32+self.a[k][(p+N-d)%N]as i32;let delta=-2*old*z;let b=self.r[d-1]as i64;let c=b+delta as i64;self.e+=c*c-b*b;self.r[d-1]+=delta}self.a[k][p]=-self.a[k][p]}fn score(&self,w:&[i64;H],l1:bool)->i64{if l1{self.r.iter().zip(w).map(|(&x,&y)|y*x.abs()as i64).sum()}else{self.r.iter().zip(w).map(|(&x,&y)|y*(x as i64)*(x as i64)).sum()}}fn rows(&self)->[i32;4]{let mut z=[0;4];for k in 0..4{z[k]=self.a[k].iter().map(|&x|x as i32).sum()}z}}
#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next()as usize%n}fn unit(&mut self)->f64{(self.next()>>11)as f64/(1u64<<53)as f64}}
fn shuffle(x:&mut[i8],r:&mut Rng){for i in(1..x.len()).rev(){let j=r.usize(i+1);x.swap(i,j)}}
fn random_good(r:&mut Rng,rows:[i32;4],skew:usize)->State{assert!((1..=2).contains(&skew));let mut a=[[1i8;N];4];for k in 0..skew{assert_eq!(rows[k],1);a[k][0]=1;for g in 1..=H{let x=if r.next()&1==0{1}else{-1};a[k][g]=x;a[k][N-g]=-x}}for k in skew..4{let t=rows[k];let fixed:i32=if t.rem_euclid(4)==3{1}else{-1};a[k][0]=fixed as i8;let gen_sum=(t-fixed)/2;let neg=((H as i32-gen_sum)/2)as usize;let mut gens=[1i8;H];for x in &mut gens[..neg]{*x=-1}shuffle(&mut gens,r);for g in 1..=H{a[k][g]=gens[g-1];a[k][N-g]=gens[g-1]}}State::new(a)}
fn parse_rows(z:Option<&String>)->[i32;4]{let v=z.map(|x|x.split(',').filter_map(|y|y.parse().ok()).collect::<Vec<i32>>()).unwrap_or_else(||vec![1,9,15,19]);if v.len()!=4||v[0]!=1||v.iter().map(|x|x*x).sum::<i32>()!=668{panic!("rows must start with 1 and have squared norm 668")}[v[0],v[1],v[2],v[3]]}
fn flip_gen(s:&mut State,k:usize,g:usize,u:&mut[(usize,usize);32],n:&mut usize){u[*n]=(k,g);u[*n+1]=(k,N-g);s.flip(k,g);s.flip(k,N-g);*n+=2}
fn make_move(s:&mut State,r:&mut Rng,u:&mut[(usize,usize);32],n:&mut usize,skew:usize){let k=r.usize(4);if k<skew{flip_gen(s,k,1+r.usize(H),u,n)}else{let mut p=1+r.usize(H);while s.a[k][p]!=1{p=1+r.usize(H)}let mut q=1+r.usize(H);while s.a[k][q]!=-1{q=1+r.usize(H)}flip_gen(s,k,p,u,n);flip_gen(s,k,q,u,n)}}
fn json(s:&State,solved:bool,elapsed:f64,moves:u64)->String{let seq=s.a.iter().map(|x|format!("[{}]",x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");let r=s.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");format!("{{\"construction\":\"cyclic Goethals-Seidel good matrices order 167\",\"solved\":{},\"energy\":{},\"elapsed_s\":{},\"moves\":{},\"row_sums\":{:?},\"residual\":[{}],\"sequences\":[{}]}}\n",solved,s.e,elapsed,moves,s.rows(),r,seq)}
fn update(s:&State,id:usize,start:Instant,atom:&AtomicI64,best:&Mutex<State>){let mut seen=atom.load(Ordering::Relaxed);while s.e<seen{match atom.compare_exchange_weak(seen,s.e,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=s.clone();let _=fs::write("good_167_live.json",json(s,false,start.elapsed().as_secs_f64(),0));eprintln!("best energy={} worker={} elapsed_s={:.3} rows={:?}",s.e,id,start.elapsed().as_secs_f64(),s.rows());return},Err(x)=>seen=x}}}
fn worker(id:usize,end:Instant,start:Instant,atom:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>,rows:[i32;4],skew:usize)->u64{let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(epoch^(id as u64+1).wrapping_mul(0x9e3779b97f4a7c15));let mut moves=0;while Instant::now()<end&&!stop.load(Ordering::Relaxed){let mut s=if rng.usize(8)==0{random_good(&mut rng,rows,skew)}else{best.lock().unwrap().clone()};for _ in 0..rng.usize(50){let mut u=[(0,0);32];let mut n=0;make_move(&mut s,&mut rng,&mut u,&mut n,skew)}let mut w=[1i64;H];let mut stale=0usize;let mut local=s.e;for step in 0..300000usize{if step&8191==0&&(Instant::now()>=end||stop.load(Ordering::Relaxed)){break}let phase=step as f64/300000.0;let l1=id%4==2;let temp=(if l1{50.0}else if id%3==0{2000.0}else if id%3==1{700.0}else{200.0})*(0.0002f64).powf(phase)+0.02;let before=s.score(&w,l1);let roll=rng.usize(1000);let count=if roll<700{1}else if roll<950{2}else{3+rng.usize(3)};let mut undo=[(0usize,0usize);32];let mut used=0;if id%4==3&&count==1{let mut bu=[(0usize,0usize);32];let mut bn=0;let mut bs=i64::MAX;for _ in 0..128{let mut tu=[(0usize,0usize);32];let mut tn=0;make_move(&mut s,&mut rng,&mut tu,&mut tn,skew);let z=s.score(&w,l1);for &(k,p)in tu[..tn].iter().rev(){s.flip(k,p)}if z<bs{bs=z;bn=tn;bu[..tn].copy_from_slice(&tu[..tn])}}for &(k,p)in&bu[..bn]{s.flip(k,p);undo[used]=(k,p);used+=1}}else{for _ in 0..count{make_move(&mut s,&mut rng,&mut undo,&mut used,skew)}}moves+=1;let delta=s.score(&w,l1)-before;if delta>0&&rng.unit()>=(-(delta as f64)/temp).exp(){for &(k,p)in undo[..used].iter().rev(){s.flip(k,p)}}else if s.e<local{local=s.e;stale=0;update(&s,id,start,&atom,&best);if s.e==0{let mut check=s.clone();check.recompute();if check.e==0{*best.lock().unwrap()=check;stop.store(true,Ordering::SeqCst);break}}}else{stale+=1}if id%2==1&&stale>40000{for j in 0..H{if s.r[j]!=0{w[j]=(w[j]+1+(s.r[j].abs()/4)as i64).min(64)}}stale=0}else if stale>80000{for _ in 0..(10+rng.usize(25)){let mut u=[(0,0);32];let mut n=0;make_move(&mut s,&mut rng,&mut u,&mut n,skew)}stale=0}}}moves}
fn main(){let z:Vec<String>=env::args().collect();let secs=z.get(1).and_then(|x|x.parse().ok()).unwrap_or(900);let threads=z.get(2).and_then(|x|x.parse().ok()).unwrap_or(4);let rows=parse_rows(z.get(3));let skew=z.get(4).and_then(|x|x.parse().ok()).unwrap_or(1usize);let mut rng=Rng(668);let initial=random_good(&mut rng,rows,skew);assert_eq!(initial.rows(),rows);eprintln!("seed energy={} rows={:?} skew={}",initial.e,rows,skew);let start=Instant::now();let end=start+Duration::from_secs(secs);let atom=Arc::new(AtomicI64::new(initial.e));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let(a,b,c)=(atom.clone(),best.clone(),stop.clone());hs.push(thread::spawn(move||worker(id,end,start,a,b,c,rows,skew)))}let moves=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut ans=best.lock().unwrap().clone();ans.recompute();let solved=ans.e==0;let out=if solved{"good_167_candidate.json"}else if skew==2{"g_matrices_167_summary.json"}else{"good_167_summary.json"};fs::write(out,json(&ans,solved,start.elapsed().as_secs_f64(),moves)).unwrap();println!("result solved={} energy={} moves={} output={}",solved,ans.e,moves,out)}
