//! Native search in the broader special family (s, s*f, s*q, s*q*f).
//! Both s and q vary.  A q-bit flip merely toggles incident correlation terms,
//! so exact residual updates remain O(83).  Zero residual is a true Golay
//! quadruple and yields H(668) by the Goethals-Seidel construction.

use std::env;
use std::fs;
use std::sync::atomic::{AtomicBool, AtomicI64, Ordering};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

#[derive(Clone)]
struct State { s:[i8;167], q:[i8;167], r:[i32;83], energy:i64 }

fn same_half(i:usize,j:usize)->bool {(i<84)==(j<84)}

impl State {
    fn new(s:[i8;167],q:[i8;167])->Self{let mut x=Self{s,q,r:[0;83],energy:0};x.recompute();x}
    fn recompute(&mut self){self.r=[0;83];for d in 1..84{for i in 0..167-d{let j=i+d;if same_half(i,j)&&self.q[i]==self.q[j]{self.r[d-1]+=self.s[i] as i32*self.s[j] as i32}}}self.energy=self.r.iter().map(|&x|(x as i64)*(x as i64)).sum()}
    fn flip_s(&mut self,p:usize){let old=self.s[p] as i32;for d in 1..84{let mut n=0i32;if p+d<167&&same_half(p,p+d)&&self.q[p]==self.q[p+d]{n+=self.s[p+d] as i32}if p>=d&&same_half(p-d,p)&&self.q[p-d]==self.q[p]{n+=self.s[p-d] as i32}let delta=-2*old*n;let before=self.r[d-1] as i64;let after=before+delta as i64;self.energy+=after*after-before*before;self.r[d-1]+=delta}self.s[p]=-self.s[p]}
    fn flip_q(&mut self,p:usize){for d in 1..84{let mut delta=0i32;if p+d<167&&same_half(p,p+d){let term=self.s[p] as i32*self.s[p+d] as i32;delta+=if self.q[p]==self.q[p+d]{-term}else{term}}if p>=d&&same_half(p-d,p){let term=self.s[p-d] as i32*self.s[p] as i32;delta+=if self.q[p-d]==self.q[p]{-term}else{term}}let before=self.r[d-1] as i64;let after=before+delta as i64;self.energy+=after*after-before*before;self.r[d-1]+=delta}self.q[p]=-self.q[p]}
    fn rank(&self)->i64{let total:i64=self.r.iter().map(|&x|x as i64).sum();let odd=self.r.iter().filter(|&&x|x&1!=0).count()as i64;self.energy+4096*total*total+4096*odd}
    fn score(&self,w:&[i64;83],l1:bool)->i64{let base:i64=if l1{self.r.iter().zip(w).map(|(&x,&y)|y*x.abs() as i64).sum()}else{self.r.iter().zip(w).map(|(&x,&y)|y*(x as i64)*(x as i64)).sum()};let total:i64=self.r.iter().map(|&x|x as i64).sum();let odd=self.r.iter().filter(|&&x|x&1!=0).count()as i64;base+if l1{512*total.abs()+512*odd}else{4096*total*total+4096*odd}}
}

#[derive(Clone,Copy)]struct Rng(u64);impl Rng{fn next(&mut self)->u64{let mut x=self.0;x^=x<<13;x^=x>>7;x^=x<<17;self.0=x;x}fn usize(&mut self,n:usize)->usize{self.next() as usize%n}fn unit(&mut self)->f64{((self.next()>>11)as f64)/(1u64<<53)as f64}}

fn parse_signs(path:&str,key:&str)->Option<[i8;167]>{let text=fs::read_to_string(path).ok()?;let start=text.find(&format!("\"{}\"",key))?;let b=text[start..].as_bytes();let mut out=[1i8;167];let(mut i,mut n)=(0,0);while i<b.len()&&n<167{if b[i]==b'-'&&i+1<b.len()&&b[i+1]==b'1'{out[n]=-1;n+=1;i+=2}else if b[i]==b'1'{out[n]=1;n+=1;i+=1}else{i+=1}}if n==167{Some(out)}else{None}}
fn initial_q()->[i8;167]{let mut q=[1i8;167];for x in &mut q[83..85]{*x=-1}q[166]=-1;q}

fn apply(state:&mut State,is_q:bool,p:usize){if is_q{state.flip_q(p)}else{state.flip_s(p)}}

fn json(state:&State,solved:bool,elapsed:f64,moves:u64)->String{let s=state.s.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");let q=state.q.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");let r=state.r.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");let f=(0..167).map(|i|if i<84{"1"}else{"-1"}).collect::<Vec<_>>().join(",");let sf=(0..167).map(|i|(state.s[i]*if i<84{1}else{-1}).to_string()).collect::<Vec<_>>().join(",");let sq=(0..167).map(|i|(state.s[i]*state.q[i]).to_string()).collect::<Vec<_>>().join(",");let sqf=(0..167).map(|i|(state.s[i]*state.q[i]*if i<84{1}else{-1}).to_string()).collect::<Vec<_>>().join(",");format!("{{\n  \"construction\": \"variable-q special Golay quadruple length 167\",\n  \"solved\": {},\n  \"energy_normalized\": {},\n  \"elapsed_s\": {:.6},\n  \"moves\": {},\n  \"residual_divided_by_4\": [{}],\n  \"s\": [{}],\n  \"q\": [{}],\n  \"f\": [{}],\n  \"sequences\": [[{}],[{}],[{}],[{}]]\n}}\n",solved,state.energy,elapsed,moves,r,s,q,f,s,sf,sq,sqf)}

fn update(state:&State,id:usize,started:Instant,atomic:&AtomicI64,best:&Mutex<State>){let rank=state.rank();let mut seen=atomic.load(Ordering::Relaxed);while rank<seen{match atomic.compare_exchange_weak(seen,rank,Ordering::SeqCst,Ordering::Relaxed){Ok(_)=>{*best.lock().unwrap()=state.clone();let _=fs::write("Find a Hadamard matrix of order 668/special_golay_167_variable_q_rank_live.json",json(state,false,started.elapsed().as_secs_f64(),0));let total:i32=state.r.iter().sum();let odd=state.r.iter().filter(|&&x|x&1!=0).count();eprintln!("best rank={} energy={} sum={} odd={} worker={} elapsed_s={:.3}",rank,state.energy,total,odd,id,started.elapsed().as_secs_f64());return},Err(x)=>seen=x}}}

fn worker(id:usize,deadline:Instant,started:Instant,atomic:Arc<AtomicI64>,best:Arc<Mutex<State>>,stop:Arc<AtomicBool>)->u64{let epoch=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()as u64;let mut rng=Rng(epoch^(id as u64+1).wrapping_mul(0x9e3779b97f4a7c15));let mut moves=0u64;while Instant::now()<deadline&&!stop.load(Ordering::Relaxed){let mut state=best.lock().unwrap().clone();for _ in 0..rng.usize(48){let iq=rng.usize(100)<38;apply(&mut state,iq,rng.usize(167))}let mut weights=[1i64;83];let mut stale=0usize;let mut local=state.rank();for step in 0..300000usize{if step&8191==0&&(Instant::now()>=deadline||stop.load(Ordering::Relaxed)){break}let phase=step as f64/300000.0;let temp=(if id%3==0{700.0}else if id%3==1{220.0}else{70.0})*(0.0005f64).powf(phase)+0.02;let l1=id%4==2;let before=state.score(&weights,l1);let roll=rng.usize(1000);let count=if roll<700{1}else if roll<950{2}else{3+rng.usize(4)};let mut chosen=[(false,0usize);8];if id%4==3&&count==1{let mut best_move=(false,0);let mut best_score=i64::MAX;for _ in 0..32{let mv=(rng.usize(100)<38,rng.usize(167));apply(&mut state,mv.0,mv.1);let score=state.score(&weights,l1);apply(&mut state,mv.0,mv.1);if score<best_score{best_score=score;best_move=mv}}chosen[0]=best_move;apply(&mut state,best_move.0,best_move.1)}else{for slot in chosen.iter_mut().take(count){*slot=(rng.usize(100)<38,rng.usize(167));apply(&mut state,slot.0,slot.1)}}moves+=1;let delta=state.score(&weights,l1)-before;if delta>0&&rng.unit()>=(-(delta as f64)/temp).exp(){for &(iq,p) in chosen[..count].iter().rev(){apply(&mut state,iq,p)}}else if state.rank()<local{local=state.rank();stale=0;update(&state,id,started,&atomic,&best);if state.energy==0{let mut check=state.clone();check.recompute();if check.energy==0{*best.lock().unwrap()=check;stop.store(true,Ordering::SeqCst);break}}}else{stale+=1}if id%2==1&&stale>40000{for j in 0..83{if state.r[j]!=0{weights[j]=(weights[j]+1+(state.r[j].abs()/4)as i64).min(64)}}stale=0}else if stale>80000{for _ in 0..(12+rng.usize(30)){let iq=rng.usize(100)<38;apply(&mut state,iq,rng.usize(167))}stale=0}}}moves}

fn main(){let args:Vec<String>=env::args().collect();let seconds=args.get(1).and_then(|x|x.parse().ok()).unwrap_or(900);let threads=args.get(2).and_then(|x|x.parse().ok()).unwrap_or(8);let path=args.get(3).expect("need JSON with 167-entry s");let seed=parse_signs(path,"s").expect("need JSON with 167-entry s");let q=parse_signs(path,"q").unwrap_or_else(initial_q);let initial=State::new(seed,q);eprintln!("seed rank={} energy={}",initial.rank(),initial.energy);let started=Instant::now();let deadline=started+Duration::from_secs(seconds);let atomic=Arc::new(AtomicI64::new(initial.rank()));let best=Arc::new(Mutex::new(initial));let stop=Arc::new(AtomicBool::new(false));let mut hs=vec![];for id in 0..threads{let(a,b,c)=(atomic.clone(),best.clone(),stop.clone());hs.push(thread::spawn(move||worker(id,deadline,started,a,b,c)))}let moves=hs.into_iter().map(|h|h.join().unwrap()).sum();let mut answer=best.lock().unwrap().clone();answer.recompute();let solved=answer.energy==0;let path=if solved{"Find a Hadamard matrix of order 668/special_golay_167_variable_q_candidate.json"}else{"Find a Hadamard matrix of order 668/special_golay_167_variable_q_rank_summary.json"};fs::write(path,json(&answer,solved,started.elapsed().as_secs_f64(),moves)).unwrap();println!("result solved={} rank={} energy={} moves={} output={}",solved,answer.rank(),answer.energy,moves,path)}
