#!/usr/bin/env python3
"""Submit a coefficient-only IGP24 batch through the SAIR public API."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from functools import reduce
from math import gcd
from pathlib import Path
from typing import Any


API_BASE = "https://api.sair.foundation"
COMPETITION_ID = "igp24"
USER_AGENT = "igp24-submit/0.1 (+https://competition.sair.foundation/competitions/igp24)"


class SubmitError(RuntimeError):
    pass


def strip_comment(line: str) -> str:
    return line.split("#", 1)[0].strip()


def parse_polynomial(line: str, line_number: int) -> str:
    text = strip_comment(line)
    parts = [part.strip() for part in text.split(",")]
    if len(parts) != 25:
        raise SubmitError(f"line {line_number}: expected 25 coefficients, got {len(parts)}")
    coeffs: list[int] = []
    for index, part in enumerate(parts):
        if not re.fullmatch(r"[+-]?[0-9]+", part):
            raise SubmitError(f"line {line_number}: a_{index} is not an integer")
        coeffs.append(int(part))
    if coeffs[0] == 0:
        raise SubmitError(f"line {line_number}: constant coefficient a_0 is zero")
    if coeffs[-1] != 1:
        raise SubmitError(f"line {line_number}: leading coefficient a_24 is not 1")
    coefficient_gcd = reduce(gcd, (abs(c) for c in coeffs), 0)
    if coefficient_gcd != 1:
        raise SubmitError(f"line {line_number}: coefficient gcd is {coefficient_gcd}, not 1")
    return ",".join(str(c) for c in coeffs)


def read_polynomials(path: Path) -> list[str]:
    raw = path.read_text(encoding="utf-8-sig")
    if len(raw.encode("utf-8")) > 1_000_000:
        raise SubmitError("submission file exceeds 1,000,000 bytes")
    polynomials: list[str] = []
    for line_number, line in enumerate(raw.splitlines(), start=1):
        text = strip_comment(line)
        if not text:
            continue
        polynomials.append(parse_polynomial(line, line_number))
    if not polynomials:
        raise SubmitError("no polynomial lines found")
    if len(polynomials) > 1000:
        raise SubmitError(f"too many polynomial lines: {len(polynomials)} > 1000")
    duplicates = len(polynomials) - len(set(polynomials))
    if duplicates:
        raise SubmitError(f"duplicate polynomial lines found: {duplicates}")
    return polynomials


def http_json(url: str, api_key: str, body: Any) -> Any:
    data = json.dumps(body, separators=(",", ":")).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        method="POST",
        headers={
            "Accept": "application/json",
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": USER_AGENT,
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise SubmitError(f"HTTP {exc.code}: {detail}") from exc
    except urllib.error.URLError as exc:
        raise SubmitError(f"request failed: {exc}") from exc


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("submission", type=Path)
    parser.add_argument("--api-key-env", default="SAIR_API_KEY")
    parser.add_argument("--description", default="IGP24 discovery batch generated by local structural search.")
    parser.add_argument("--dry-run", action="store_true", help="validate and summarize without submitting")
    parser.add_argument("--yes", action="store_true", help="submit without interactive confirmation")
    args = parser.parse_args(argv)

    polynomials = read_polynomials(args.submission)
    print(f"polynomials={len(polynomials)}")
    print(f"bytes={len(args.submission.read_bytes())}")
    if args.dry_run:
        print("dry_run=true")
        return 0

    api_key = os.environ.get(args.api_key_env, "").strip()
    if not api_key:
        raise SubmitError(f"set {args.api_key_env} before running")
    if not args.yes:
        answer = input(f"Submit {len(polynomials)} polynomials to SAIR IGP24? Type 'submit' to continue: ")
        if answer.strip() != "submit":
            print("submission cancelled")
            return 0

    body = {
        "payload": {"polynomials": polynomials},
        "meta": {"description": args.description[:500]},
    }
    url = f"{API_BASE}/api/public/v1/competitions/{COMPETITION_ID}/submissions"
    payload = http_json(url, api_key=api_key, body=body)
    data = payload.get("data", payload)
    print(json.dumps({
        "submissionId": data.get("submissionId") or data.get("id"),
        "batchId": data.get("batchId"),
        "status": data.get("status"),
        "createdAt": data.get("createdAt"),
        "verifiedCount": len(data.get("verifiedPolynomials") or []),
        "failedCount": len(data.get("failedPolynomials") or []),
    }, indent=2))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except SubmitError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2)
