#!/usr/bin/env python3
"""Source totally real cyclic IGP24 candidates from cyclotomic periods.

For the default conductor p=97, the multiplicative group modulo p is cyclic of
order 96. The subgroup of order 4 generated by g^24 contains -1, so the Gaussian
period

    sum_{h in H} zeta_p^h

lies in the maximal real cyclotomic field and has 24 conjugates. Its period
polynomial is a totally real cyclic degree-24 candidate, expected label 24T1.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
import time
from pathlib import Path
from typing import Any

import mpmath as mp
import sympy as sp


SOURCE = "cyclotomic Gaussian period"
PROVENANCE = "conductor 97 cyclic degree-24 real subfield; LMFDB group 24T1 is C24"


def prime_factors(n: int) -> list[int]:
    factors: list[int] = []
    d = 2
    while d * d <= n:
        if n % d == 0:
            factors.append(d)
            while n % d == 0:
                n //= d
        d += 1 if d == 2 else 2
    if n > 1:
        factors.append(n)
    return factors


def primitive_root_mod_prime(p: int) -> int:
    factors = prime_factors(p - 1)
    for g in range(2, p):
        if all(pow(g, (p - 1) // q, p) != 1 for q in factors):
            return g
    raise ValueError(f"no primitive root found modulo {p}")


def period_polynomial(p: int, degree: int, digits: int) -> tuple[list[int], dict[str, Any]]:
    if (p - 1) % degree != 0:
        raise ValueError("degree must divide p-1")
    subgroup_order = (p - 1) // degree
    if subgroup_order % 2 != 0:
        raise ValueError("subgroup order must be even so -1 can lie in the subgroup")

    g = primitive_root_mod_prime(p)
    subgroup = sorted({pow(g, degree * k, p) for k in range(subgroup_order)})
    if p - 1 not in subgroup:
        raise ValueError("chosen subgroup does not contain -1; period may not be totally real")

    reps = [pow(g, j, p) for j in range(degree)]
    mp.mp.dps = digits
    roots = []
    for rep in reps:
        total = mp.mpc(0)
        for h in subgroup:
            total += mp.e ** (2j * mp.pi * ((rep * h) % p) / p)
        roots.append(mp.re(total))

    coeffs_high = [mp.mpf(1)]
    for root in roots:
        coeffs_high.append(mp.mpf(0))
        for index in range(len(coeffs_high) - 1, 0, -1):
            coeffs_high[index] -= root * coeffs_high[index - 1]

    rounded_high: list[int] = []
    max_error = mp.mpf(0)
    for coeff in coeffs_high:
        rounded = int(mp.nint(coeff))
        rounded_high.append(rounded)
        max_error = max(max_error, abs(coeff - rounded))

    coeffs_low = list(reversed(rounded_high))
    metadata = {
        "prime": p,
        "degree": degree,
        "primitive_root": g,
        "subgroup_order": subgroup_order,
        "subgroup": subgroup,
        "max_rounding_error": mp.nstr(max_error, 40),
    }
    return coeffs_low, metadata


def validate_coefficients(coeffs: list[int], expected_degree: int) -> dict[str, Any]:
    x = sp.Symbol("x")
    poly = sp.Poly.from_list(list(reversed(coeffs)), gens=x, domain=sp.ZZ)
    coefficient_gcd = 0
    for coeff in coeffs:
        coefficient_gcd = math.gcd(coefficient_gcd, abs(coeff))
    return {
        "degree": poly.degree(),
        "constant": coeffs[0],
        "leading": coeffs[-1],
        "coefficient_gcd": coefficient_gcd,
        "irreducible": bool(poly.is_irreducible),
        "real_roots": int(poly.count_roots(sp.S.NegativeInfinity, sp.S.Infinity)),
        "valid_shape": poly.degree() == expected_degree and coeffs[0] != 0 and coeffs[-1] == 1 and coefficient_gcd == 1,
    }


def write_outputs(row: dict[str, Any], output: Path, report: Path, metadata: dict[str, Any]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["label", "r", "polynomial", "source", "provenance", "conductor", "note"]
    with output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerow(row)
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(
        json.dumps(
            {
                "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "row": row,
                "metadata": metadata,
            },
            indent=2,
        ),
        encoding="utf-8",
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prime", type=int, default=97)
    parser.add_argument("--degree", type=int, default=24)
    parser.add_argument("--label", default="24T1")
    parser.add_argument("--digits", type=int, default=180)
    parser.add_argument("--output", type=Path, default=Path("data/igp24/cyclotomic_period_candidates.csv"))
    parser.add_argument("--report", type=Path, default=Path("data/igp24/cyclotomic_period_candidates_report.json"))
    args = parser.parse_args(argv)

    coeffs, metadata = period_polynomial(args.prime, args.degree, args.digits)
    validation = validate_coefficients(coeffs, args.degree)
    if not validation["valid_shape"]:
        raise ValueError(f"invalid IGP24 coefficient shape: {validation}")
    row = {
        "label": args.label,
        "r": validation["real_roots"],
        "polynomial": ",".join(str(coeff) for coeff in coeffs),
        "source": SOURCE,
        "provenance": PROVENANCE,
        "conductor": args.prime,
        "note": f"primitive_root={metadata['primitive_root']}; subgroup={metadata['subgroup']}",
    }
    metadata["validation"] = validation
    write_outputs(row, args.output, args.report, metadata)
    print(f"output={args.output}")
    print(f"report={args.report}")
    print(f"label={args.label}")
    print(f"r={validation['real_roots']}")
    print(f"irreducible={validation['irreducible']}")
    print(f"polynomial={row['polynomial']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
