use schemars::r#gen::SchemaSettings;
use schemars::schema::RootSchema;

use crate::models::action::TypedAction;

pub fn generate_schema() -> RootSchema {
    // Explicitly configure schemars for JSON Schema 2020-12 (Draft 2020-12)
    // Schemars doesn't natively support 2020-12 perfectly, but Draft 2019-09/2020-12 
    // are compatible in most structures generated by schemars. We use `openapi3` 
    // or standard draft07 config, but we can set the meta schema manually.
    
    let settings = SchemaSettings::draft07().with(|s| {
        s.option_nullable = true;
        s.option_add_null_type = false;
    });
    
    let generator = settings.into_generator();
    let mut schema = generator.into_root_schema_for::<TypedAction>();
    
    // Explicitly request JSON Schema 2020-12 via the $schema field
    schema.schema.metadata().id = Some("https://json-schema.org/draft/2020-12/schema".to_string());
    
    schema
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_schema_2020_12() {
        let schema = generate_schema();
        let schema_json = serde_json::to_string(&schema).unwrap();
        assert!(schema_json.contains("2020-12"));
    }
}
